#!/usr/bin/env bash
#  ██╗  ██╗██╗  ██╗ ██████╗██╗  ██╗██████╗ ██████╗ 
#  ██║  ██║██║  ██║██╔════╝██║ ██╔╝╚════██╗██╔══██╗
#  ███████║███████║██║     █████╔╝  █████╔╝██████╔╝
#  ██╔══██║╚════██║██║     ██╔═██╗  ╚═══██╗██╔══██╗
#  ██║  ██║     ██║╚██████╗██║  ██╗██████╔╝██║  ██║
#  ╚═╝  ╚═╝     ╚═╝ ╚═════╝╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝
#  Author  :  z0mbi3
#  Url     :  https://github.com/gh0stzk/dotfiles
#  About   :  This file will configure and launch the rice.
#

# Set bspwm configuration for h4ck3r
set_bspwm_config() {
	bspc config border_width 0
	bspc config top_padding 43
	bspc config bottom_padding 2
	bspc config left_padding 2
	bspc config right_padding 2
	bspc config normal_border_color "#578a29"
	bspc config active_border_color "#9cf542"
	bspc config focused_border_color "#6DDE00"
	bspc config presel_feedback_color "#00fa5c"
}

# Reload terminal colors
set_term_config() {
	cat >"$HOME"/.config/alacritty/rice-colors.toml <<EOF
# (Hack The box) color scheme for h4ck3r Rice

# Default colors
[colors.primary]
background = "#0c1018"
foreground = "#1947e0"

# Cursor colors
[colors.cursor]
cursor = "#00cc00"
text = "#000000"

# Normal colors
[colors.normal]
black = "#4A9801"
red = "#6DDE00"
green = "#00fa5c"
yellow = "#76EA00"
blue =  "#578a29"
magenta = "#9cf542"
cyan = "#539e06"
white = "#00ff59"

# Bright colors
[colors.bright]
black = "#03198a"
red = "#0800ff"
green = "#4145b0"
yellow = "#025dd4"
blue = "#7eb3f7"
magenta = "#220991"
cyan = "#3a11f0"
white = "#3b5eed"
EOF
}

# Set kitty colorscheme
set_kitty_config() {
  cat >"$HOME"/.config/kitty/current-theme.conf <<EOF
## This file is autogenerated, do not edit it, instead edit the Theme.sh file inside the rice directory.
## (Hack The box) color scheme for h4ck3r Rice


# The basic colors
foreground              #1947e0
background              #0c1018
selection_foreground    #0c1018
selection_background    #6DDE00

# Cursor colors
cursor                  #00cc00
cursor_text_color       #000000

# URL underline color when hovering with mouse
url_color               #00fa5c

# Kitty window border colors
active_border_color     #9cf542
inactive_border_color   #578a29
bell_border_color       #76EA00

# Tab bar colors
active_tab_foreground   #0c1018
active_tab_background   #9cf542
inactive_tab_foreground #0c1018
inactive_tab_background #578a29
tab_bar_background      #0c1018

# The 16 terminal colors

# black
color0 #4A9801
color8 #03198a

# red
color1 #6DDE00
color9 #0800ff

# green
color2  #00fa5c
color10 #4145b0

# yellow
color3  #76EA00
color11 #025dd4

# blue
color4  #578a29
color12 #7eb3f7

# magenta
color5  #9cf542
color13 #220991

# cyan
color6  #539e06
color14 #3a11f0

# white
color7  #00ff59
color15 #3b5eed
EOF

killall -USR1 kitty
}

# Set compositor configuration
set_picom_config() {
	sed -i "$HOME"/.config/bspwm/picom.conf \
		-e "s/normal = .*/normal =  { fade = true; shadow = true; }/g" \
		-e "s/shadow-color = .*/shadow-color = \"#000000\"/g" \
		-e "s/corner-radius = .*/corner-radius = 6/g" \
		-e "s/\".*:class_g = 'Alacritty'\"/\"100:class_g = 'Alacritty'\"/g" \
    -e "s/\".*:class_g = 'kitty'\"/\"100:class_g = 'kitty'\"/g" \
		-e "s/\".*:class_g = 'FloaTerm'\"/\"100:class_g = 'FloaTerm'\"/g"
}

# Set dunst notification daemon config
set_dunst_config() {
	sed -i "$HOME"/.config/bspwm/dunstrc \
		-e "s/transparency = .*/transparency = 0/g" \
		-e "s/frame_color = .*/frame_color = \"#0c1018\"/g" \
		-e "s/separator_color = .*/separator_color = \"#6DDE00\"/g" \
		-e "s/font = .*/font = JetBrainsMono NF Medium 9/g" \
		-e "s/foreground='.*'/foreground='#1947e0'/g"

	sed -i '/urgency_low/Q' "$HOME"/.config/bspwm/dunstrc
	cat >>"$HOME"/.config/bspwm/dunstrc <<-_EOF_
		[urgency_low]
		timeout = 3
		background = "#0c1018"
		foreground = "#76EA00"

		[urgency_normal]
		timeout = 6
		background = "#0c1018"
		foreground = "#76EA00"

		[urgency_critical]
		timeout = 0
		background = "#0c1018"
		foreground = "#76EA00"
	_EOF_
}

# Set eww colors
set_eww_colors() {
	cat >"$HOME"/.config/bspwm/eww/colors.scss <<EOF
// Eww colors for h4ck3r rice
\$bg: #0c1018;
\$bg-alt: #1B2333;
\$fg: #1947e0;
\$black: #4A9801;
\$lightblack: #262831;
\$red: #6DDE00;
\$blue: #578a29;
\$cyan: #539e06;
\$magenta: #9cf542;
\$green: #00fa5c;
\$yellow: #76EA00;
\$archicon: #0f94d2;
EOF
}

# Set jgmenu colors for h4ck3r
set_jgmenu_colors() {
	sed -i "$HOME"/.config/bspwm/jgmenurc \
		-e 's/color_menu_bg = .*/color_menu_bg = #0c1018/' \
		-e 's/color_norm_fg = .*/color_norm_fg = #1947e0/' \
		-e 's/color_sel_bg = .*/color_sel_bg = #1B2333/' \
		-e 's/color_sel_fg = .*/color_sel_fg = #1947e0/' \
		-e 's/color_sep_fg = .*/color_sep_fg = #4A9801/'
}

# Set rofi colors
set_launcher_config() {
	cat >"$HOME"/.config/bspwm/src/rofi-themes/shared.rasi <<EOF
// Rofi colors for h4ck3r

* {
    font: "JetBrainsMono NF Bold 9";
    background: #0c1018;
    background-alt: #0c1018E0;
    foreground: #1947e0;
    selected: #1B2333;
    active: #00fa5c;
    urgent: #6DDE00;
    
    img-background: url("~/.config/bspwm/rices/h4ck3r/rofi.webp", width);
}
EOF
}

# Launch the bar
launch_bars() {

	for mon in $(polybar --list-monitors | cut -d":" -f1); do
		MONITOR=$mon polybar -q c0mrad -c "${rice_dir}"/config.ini &
	done

}

### ---------- Apply Configurations ---------- ###

set_bspwm_config
set_term_config
set_kitty_config
set_picom_config
set_eww_colors
set_jgmenu_colors
set_dunst_config
set_launcher_config
launch_bars
