
shadow = false;
shadow-radius = 1;
shadow-opacity = .75
shadow-offset-x = -7;
shadow-offset-y = -7;

shadow-exclude = [ 
    "name = 'Notification'",
    "override_redirect = 1 && !WM_CLASS@:s",
    "class_g ?= 'Dmenu'",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
    "_GTK_FRAME_EXTENTS@:c",
    "class_g ?= 'Polybar'",
    "class_g ?= 'Notify-osd'",
    "class_g ?= 'trayer'" 
];


#fading = false;

#fade-in-step = 0.098;
#fade-out-step = 0.3;
#fade-delta = 3
#fade-exclude = []
#no-fading-openclose = true

frame-opacity = 1.0;
inactive-opacity-override = false;
active-opacity = 1.0;
inactive-dim = 0.0;

focus-exclude = [ "class_g = 'Cairo-clock'" ];

opacity-rule = [ 
"99:class_g *?= 'Org.gnome.Nautilus'",
"100:class_g *?= 'surf' && name *?='suckless.org'",
"100:name *?= 'newsboat'",
"95:class_g = 'XTerm' && !_NET_WM_STATE@:32a", 
"0:_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'", 
"96:_NET_WM_STATE@:32a *= '_NET_WM_STATE_STICKY'" 
];

# Parameters for background blurring, see the *BLUR* section for more information.
# blur-method = 
# blur-size = 12
#
# blur-deviation = false

# Blur background of semi-transparent / ARGB windows. 
# Bad in performance, with driver-dependent behavior. 
# The name of the switch may change without prior notifications.
#
#blur-background = false

# Blur background of windows when the window frame is not opaque. 
# Implies:
#    blur-background 
# Bad in performance, with driver-dependent behavior. The name may change.
#
# blur-background-frame = false


# Use fixed blur strength rather than adjusting according to window opacity.
# blur-background-fixed = false


# Specify the blur convolution kernel, with the following format:
# example:
#   blur-kern = "5,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1";
#
# blur-kern = ''
#blur-kern = "3x3box";


# Exclude conditions for background blur.
# blur-background-exclude = []
#blur-background-exclude = [
#  "window_type = 'dock'",
#  "window_type = 'desktop'",
#  "_GTK_FRAME_EXTENTS@:c"
#];


backend = "xrender";
vsync = true;
dbus = false;
mark-wmwin-focused = true;

#corner-radius = 10.0;
#detect-rounded-corners = true;

#rounded-corners-exclude = [
# "_PICOM_ROUNDED@:32c = 1",
#  "class_g = 'dmenu'",
#  "class_g = 'Viewnior'",
#  "class_g = 'mpv'",
#  "class_g = 'Polybar'"
#];

detect-client-opacity = true;
refresh-rate = 60;
use-ewmh-active-win = true;
unredir-if-possible = false;
detect-transient = true;
detect-client-leader = true;
use-damage = false;
log-level = "warn";
# show-all-xerrors = false


wintypes : 
{
  tooltip : 
  {
    fade = false;
    shadow = false;
    dropdown_menu = 1.0;
    popup_menu = 1.0;
    opacity = 1.0;
    focus = true;
  };
  fullscreen : 
  {
    fade = true;
    shadow = false;
    opacity = 1.0;
    focus = true;
  };
};

