#!/bin/sh

bat=/sys/class/power_supply/BAT0/
per="$(cat "$bat/capacity")"

battery_status () {
	if [ -d "$bat" ]; then
		printf "true"
	else
		printf "false"
	fi
}

icon() {

    [ "$(cat "$bat/status")" = Charging ] && icon="images/battery_charging.png" && echo "$icon" && exit

    if [ "$per" -gt "90" ]; then
        icon="images/battery_100.png"
    elif [ "$per" -gt "80" ]; then
        icon="images/battery_90.png"
    elif [ "$per" -gt "70" ]; then
        icon="images/battery_70.png"
    elif [ "$per" -gt "60" ]; then
        icon="images/battery_50.png"
    elif [ "$per" -gt "50" ]; then
        icon="images/battery_50.png"
    elif [ "$per" -gt "40" ]; then
        icon="images/battery_30.png"
    elif [ "$per" -gt "30" ]; then
        icon="images/battery_30.png"
    elif [ "$per" -gt "20" ]; then
        icon="images/battery_20.png"
    elif [ "$per" -gt "10" ]; then
        icon="images/battery_20.png"
    elif [ "$per" -gt "0" ]; then
        icon="images/battery_empty.png"
    else
        icon="images/battery_empty.png"
    fi
    echo "$icon"
}

percent() {
    echo "$per"
}

[ "$1" = "battery_status" ] && battery_status && exit
[ "$1" = "icon" ] && icon && exit
[ "$1" = "percent" ] && percent && exit
