#!/usr/bin/env bash
#  ███╗   ██╗███████╗████████╗██╗    ██╗ ██████╗ ██████╗ ██╗  ██╗
#  ████╗  ██║██╔════╝╚══██╔══╝██║    ██║██╔═══██╗██╔══██╗██║ ██╔╝
#  ██╔██╗ ██║█████╗     ██║   ██║ █╗ ██║██║   ██║██████╔╝█████╔╝
#  ██║╚██╗██║██╔══╝     ██║   ██║███╗██║██║   ██║██╔══██╗██╔═██╗
#  ██║ ╚████║███████╗   ██║   ╚███╔███╔╝╚██████╔╝██║  ██║██║  ██╗
#  ╚═╝  ╚═══╝╚══════╝   ╚═╝    ╚══╝╚══╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
#	gh0stzk
#	https://github.com/gh0stzk/dotfiles
#	This script checks if you are connected to the internet and sets values.
#	23.09.2023 13:39:59

ID=$(ip link | awk '/state UP/ {print $2}' | tr -d :)
SSID=""
ICON="images/wifi.png"

if command -v iwgetid >/dev/null 2>&1 ; then
    SSID=$(iwgetid -r)
fi

ping_servers=("archlinux.org" "google.com")

is_online() {
    for server in "${ping_servers[@]}"; do
        if ping -c 1 "$server" &>/dev/null; then
            return 0  # Online
        fi
    done
    return 1  # Offline
}

if is_online; then
    if [[ $ID == e* ]]; then
        STATUS="$ID"
    else
        STATUS="$SSID"
    fi
else
    STATUS="Offline"
    ICON="images/no-wifi.png"
fi

case "$1" in
    --stat) echo "$STATUS" ;;
    --icon) echo "$ICON" ;;
esac
