#!/usr/bin/env bash

infocenter(){
FILE="$HOME/.cache/eww_z0mbi3.dashboard"

if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	eww --config $HOME/.config/bspwm/rices/z0mbi3/dashboard open dashboard
else
	eww --config $HOME/.config/bspwm/rices/z0mbi3/dashboard close dashboard
	rm "$FILE"
fi
}

calendar(){
LOCK_FILE="$HOME/.cache/eww-z0mbi3-calendar.lock"

if [[ ! -f "$LOCK_FILE" ]]; then
    touch "$LOCK_FILE"
    eww -c $HOME/.config/bspwm/rices/z0mbi3/bar open calendar
else
    eww -c $HOME/.config/bspwm/rices/z0mbi3/bar close calendar
    rm "$LOCK_FILE"
fi
}

case "$1" in
  --infocenter)
	infocenter;;
  --calendar)
	calendar;;
esac
