#!/bin/bash

EWW=`which eww`
CFG="$HOME/.config/bspwm/$RICETHEME/arin"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} --config "$CFG" --restart open-many \
		   search \
		   apps \
		   weather \
		   music \
		   system
}

## Launch or close widgets accordingly
run_eww
