#!/usr/bin/env bash

mplayer() {
    LOCKFILE="$HOME/.cache/eww-cris-mplayer.lock"

if [[ ! -f "$LOCKFILE" ]]; then
    touch "$LOCKFILE"
    eww open music -c ~/.config/bspwm/rices/cristina/widgets/
elif [[ -f "$LOCKFILE" ]]; then
    eww close music -c ~/.config/bspwm/rices/cristina/widgets/
    rm "$LOCKFILE"
fi
}

mplayer
