#!/usr/bin/env bash

launcher() {
    LOCK_FILE_LAUNCHER="$HOME/.cache/eww-launcher.lock"

run() {
    eww open launchermenu -c ~/.config/bspwm/rices/pamela/widgets/
}

# Open widgets
if [[ ! -f "$LOCK_FILE_LAUNCHER" ]]; then
    eww close launchermenu -c ~/.config/bspwm/rices/pamela/widgets/
    touch "$LOCK_FILE_LAUNCHER"
    run && echo "ok good!"
elif [[ -f "$LOCK_FILE_LAUNCHER" ]]; then
    eww close launchermenu -c ~/.config/bspwm/rices/pamela/widgets/
    rm "$LOCK_FILE_LAUNCHER" && echo "closed"
fi
}

launcher
