require("gh0st.plugins-setup")
require("gh0st.core.options")
require("gh0st.core.keymaps")
require("gh0st.core.colorscheme")
require("gh0st.plugins.nvim-tree")
require("gh0st.plugins.lualine")
require("gh0st.plugins.colorizer")
