#! /bin/sh

sxhkd &
picom &
nitrogen --restore &
/home/gh0st/.config/polybar/launch.sh &
lxpolkit &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
# fix power settings
#/usr/bin/xfce4-power-manager &
nm-applet &
volumeicon &


bspc monitor VGA1 -d g h 0 s t

#### BSPWM configuration #### 
#bspc config border_radius                8 
bspc config border_width                  1 
bspc config window_gap                    10 
bspc config top_padding                   10 
bspc config bottom_padding                0 
bspc config left_padding                  0 
bspc config right_padding                 0 
bspc config single_monocle                false
#bspc config click_to_focus                true 
bspc config split_ratio                   0.50 
bspc config borderless_monocle            true 
bspc config gapless_monocle               true
#bspc config focus_by_distance             true 
bspc config focus_follows_pointer         true 
#bspc config history_aware_focus           true 
bspc config remove_disabled_monitors      true 
bspc config merge_overlapping_monitors    true 
bspc config pointer_modifier mod4 
bspc config pointer_action1 move 
bspc config pointer_action2 resize_side 
bspc config pointer_action3 resize_corner
#bspc config automatic_scheme      spiral

SPACES=$(bspc query -D)
for SPACE in $SPACES
do
  bspc config -d ${SPACE} window_gap      10
  bspc config -d ${SPACE} top_padding     20
  bspc config -d ${SPACE} bottom_padding  20
  bspc config -d ${SPACE} left_padding   40
  bspc config -d ${SPACE} right_padding  40
done

#### BSPWM coloring #### 
bspc config normal_border_color		      "#4C3A6D" 
bspc config active_border_color	          "#4C3A6D"
bspc config focused_border_color	      "#785DA5"
bspc config presel_feedback_color	      "#6272a4" 
#bspc config urgent_border_color 	      "#dd2727" 

bspc rule -a Gimp desktop='^3' state=floating follow=on 
bspc rule -a firefox desktop='^3' state=pseudo_tiled follow=on rectangle=1280x800+0+0 center=on
bspc rule -a firefox:firefox state=floating rectangle=748x478+0+0 center=on
bspc rule -a firefox:Firefox state=floating rectangle=499x289+0+0 center=on

bspc rule -a whatsapp-desktop desktop='^4' state=pseudo_tiled rectangle=1024x650+0+0 follow=on center=on
bspc rule -a TelegramDesktop desktop='^4' follow=on
bspc rule -a Spotify desktop='^4' state=floating follow=on center=on
bspc rule -a qtws desktop='^4' state=floating follow=on center=on

bspc rule -a Epsxe desktop='^5' follow=on
bspc rule -a Snes9x-gtk desktop='^5' state=floating follow=on
bspc rule -a m64py desktop='^5' state=floating follow=on
bspc rule -a Fceux desktop='^5' state=floating follow=on
bspc rule -a Visualboyadvance-m desktop='^5' state=floating follow=on
bspc rule -a Desmume desktop='^5' state=floating follow=on center=on
bspc rule -a minecraft-launcher desktop='^5' state=pseudo_tiled rectangle=900x680+0+0 follow=on

bspc rule -a Pavucontrol state=floating follow=on center=on 

bspc rule -a Tilix state=pseudo_tiled center=on
bspc rule -a Org.gnome.Nautilus state=pseudo_tiled center=on
bspc rule -a Mirage state=floating center=on
bspc rule -a Totem state=floating center=on
bspc rule -a mpv state=floating center=on
bspc rule -a SimpleScreenRecorder state=floating

