#!/usr/bin/env bash

video_path="$2"

start(){

	if [[ ! "$video_path" =~ \.(mp4|mkv|gif)$ ]]; then
        echo "[-] El archivo no tiene una extensión de video válida" >&2
        exit 1
    fi

	SCREENS=$(xrandr | awk '/ connected/ {print $4}')
	for item in $SCREENS
	do
		xwinwrap -g "$item" -un -fdt -ni -b -nf -- mpv --hwdec=auto -vo x11 --no-audio --no-border --no-config --no-window-dragging --no-input-default-bindings --no-osd-bar --no-sub --loop -wid WID ${video_path} > /dev/null 2>&1 &
	done
}

stop(){
	killall xwinwrap > /dev/null 2>&1
}

print_help() {
	echo "Usage: AnimatedWall [--start] [--stop] \"video_path.mp4\""
	echo "--start Start playback of video file."
	echo "--stop Stop active playback."
}

if [ $# -eq 0 ]; then
    print_help
    exit 1
fi

while [[ "$#" -gt 0 ]]; do
	case $1 in
		--start) start; shift ;;
		--stop) stop; shift ;;
		*) echo "Unknown parameter: $1" ;;
	esac
	shift
done
