#!/usr/bin/env bash
# Author : rxyhn

DIR="$HOME/.config/bspwm/src/assets"
BRIGHTNESS_STEPS=5
MIN_BRIGHTNESS=2

function get_brightness {
  brightnessctl i | grep -oP '\(\K[^%\)]+'
}

function send_notification {
  icon="$DIR/brightness.svg"
  brightness=$(get_brightness)
  # Make the bar with the special character ─ (it's not dash -)
  # https://en.wikipedia.org/wiki/Box-drawing_character
  bar=$(seq -s "─" 0 $((brightness / 5)) | sed 's/[0-9]//g')
  # Send the notification
  dunstify "Brightness $brightness%" -i $icon -r 5555 -u normal -h int:value:$(($brightness))
}

function adjust_brightness {
  current=$(get_brightness)
  
  case $1 in
    up)
      if [ "$current" -eq $MIN_BRIGHTNESS ]; then
        # If at MIN_BRIGHTNESS, go to 5%
        brightnessctl set 5% -q
      else
        # Normal 5% increase
        brightnessctl set "${BRIGHTNESS_STEPS:-5}%+" -q
      fi
      ;;
    down)
      if [ "$current" -le $((MIN_BRIGHTNESS + BRIGHTNESS_STEPS)) ]; then
        # If at or below 7%, go to MIN_BRIGHTNESS
        brightnessctl set $MIN_BRIGHTNESS% -q
      else
        # Normal 5% decrease
        brightnessctl set "${BRIGHTNESS_STEPS:-5}%-" -q
      fi
      ;;
  esac
  
  send_notification
}

case $1 in
  up)
    adjust_brightness up
    ;;
  down)
    adjust_brightness down
    ;;
esac
