#!/usr/bin/env bash
#  ██╗  ██╗███████╗██╗   ██╗██████╗  ██████╗  █████╗ ██████╗ ██████╗
#  ██║ ██╔╝██╔════╝╚██╗ ██╔╝██╔══██╗██╔═══██╗██╔══██╗██╔══██╗██╔══██╗
#  █████╔╝ █████╗   ╚████╔╝ ██████╔╝██║   ██║███████║██████╔╝██║  ██║
#  ██╔═██╗ ██╔══╝    ╚██╔╝  ██╔══██╗██║   ██║██╔══██║██╔══██╗██║  ██║
#  ██║  ██╗███████╗   ██║   ██████╔╝╚██████╔╝██║  ██║██║  ██║██████╔╝
#  ╚═╝  ╚═╝╚══════╝   ╚═╝   ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝
#  gh0stzk                             ██╗      █████╗ ██╗   ██╗ ██████╗ ██╗   ██╗████████╗
#  https://github.com/gh0stzk/dotfiles ██║     ██╔══██╗╚██╗ ██╔╝██╔═══██╗██║   ██║╚══██╔══╝
#  31.10.2024 15:30:00                 ██║     ███████║ ╚████╔╝ ██║   ██║██║   ██║   ██║
#                                      ██║     ██╔══██║  ╚██╔╝  ██║   ██║██║   ██║   ██║
#                                      ███████╗██║  ██║   ██║   ╚██████╔╝╚██████╔╝   ██║
#                                      ╚══════╝╚═╝  ╚═╝   ╚═╝    ╚═════╝  ╚═════╝    ╚═╝

# Get the current layout
CURRENT=$(setxkbmap -query | awk '/layout/ {print $2}')

# Layouts. You can add yours.
declare -A LAYOUTS=(
    ["US English"]="us"
    ["ES América Latina"]="latam"
    ["ES España"]="es"
    ["FR France"]="fr"
    ["DE Deutschland"]="de"
    ["RU Россия"]="ru"
    ["IT Italia"]="it"
    ["PT Brasil"]="br"
)

# Show rofi menu
show_rofi_menu() {
    local options=""
    for layout in "${!LAYOUTS[@]}"; do
        options+="$layout\n"
    done
    echo -e "${options%\\n}" | rofi \
        -dmenu \
        -p "Keyboard Layout" \
        -mesg "Current layout --> $CURRENT" \
        -markup-rows \
        -theme "$HOME/.config/bspwm/src/rofi-themes/Keyboard.rasi"
}

# Select and apply the layout
selected=$(show_rofi_menu)
if [[ -n "$selected" && -n "${LAYOUTS[$selected]}" ]]; then
    setxkbmap "${LAYOUTS[$selected]}"
fi
