#!/usr/bin/env bash
#  ██████╗ ██╗ ██████╗███████╗
#  ██╔══██╗██║██╔════╝██╔════╝        gh0stzk
#  ██████╔╝██║██║     █████╗          https://github.com/gh0stzk/dotfiles
#  ██╔══██╗██║██║     ██╔══╝          08.12.2023 08:48:08
#  ██║  ██║██║╚██████╗███████╗
#  ╚═╝  ╚═╝╚═╝ ╚═════╝╚══════╝
#
#            ███████╗███████╗██╗     ███████╗ ██████╗████████╗ ██████╗ ██████╗
#            ██╔════╝██╔════╝██║     ██╔════╝██╔════╝╚══██╔══╝██╔═══██╗██╔══██╗
#            ███████╗█████╗  ██║     █████╗  ██║        ██║   ██║   ██║██████╔╝
#            ╚════██║██╔══╝  ██║     ██╔══╝  ██║        ██║   ██║   ██║██╔══██╗
#            ███████║███████╗███████╗███████╗╚██████╗   ██║   ╚██████╔╝██║  ██║
#            ╚══════╝╚══════╝╚══════╝╚══════╝ ╚═════╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝

# Some vars
bspwm_dir="$HOME/.config/bspwm"
read -r current_rice < "$bspwm_dir"/.rice
rofi_command="rofi -dmenu -theme $bspwm_dir/src/rofi-themes/RiceSelector.rasi"

# Variables to try to define the correct size of the images for your resolution
monitor_res=$(($(xdpyinfo | awk '/dimensions/{print $2}' | cut -d 'x' -f1) * 17 / $(xdpyinfo | awk '/resolution/{print $2}' | cut -d 'x' -f1)))
rofi_override="element-icon{size:${monitor_res}px;}"

# List rices
mapfile -t rices < <(find "$bspwm_dir/rices/" -mindepth 1 -maxdepth 1 -type d -printf '%P\n' | sort)

selected_index=$(printf '%s\n' "${rices[@]}" | awk -v cur="$current_rice" '$0==cur {print NR-1; exit}')

# Show the rofi selection menu.
selected=$(
    for rice in "${rices[@]}"; do
        echo -e "$rice\0icon\x1f$bspwm_dir/rices/$rice/preview.webp"
    done | $rofi_command -theme-str "$rofi_override" -selected-row "$selected_index"
)

# If a valid option was selected, write the value to the configuration file and change theme.
[[ -n "$selected" && "$selected" != "$current_rice" ]] && {
    echo "$selected" > "$bspwm_dir"/.rice
	"${bspwm_dir}"/rices/"${selected}"/Theme.sh 
}
