#!/usr/bin/env python3

#  ██████╗ ██╗ ██████╗███████╗    ███████╗██████╗ ██╗████████╗ ██████╗ ██████╗
#  ██╔══██╗██║██╔════╝██╔════╝    ██╔════╝██╔══██╗██║╚══██╔══╝██╔═══██╗██╔══██╗
#  ██████╔╝██║██║     █████╗      █████╗  ██║  ██║██║   ██║   ██║   ██║██████╔╝
#  ██╔══██╗██║██║     ██╔══╝      ██╔══╝  ██║  ██║██║   ██║   ██║   ██║██╔══██╗
#  ██║  ██║██║╚██████╗███████╗    ███████╗██████╔╝██║   ██║   ╚██████╔╝██║  ██║
#  ╚═╝  ╚═╝╚═╝ ╚═════╝╚══════╝    ╚══════╝╚═════╝ ╚═╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝
#	Author	:	gh0stzk
#	Repo	:	https://github.com/gh0stzk/dotfiles
#	Info	:	This app will control some aspects of the theme you are in.
#				If you change the theme you will need to reopen the app.
#	App		:	First release v.1 06.10.2024 07:45:28

import gi
import os
import re
import subprocess

gi.require_version("Gtk", "3.0")
from gi.repository import Gtk, Gdk

class ConfigurarTemaWindow(Gtk.Window):
    def __init__(self):
        Gtk.Window.__init__(self, title="Configure BSPWM Theme")
        self.set_border_width(10)
        self.set_default_size(544, 257)

		# Apply JetBrainsMono Nerd Font
        self.set_fuente_personalizada()

        # Get Rice var
        self.tema = self.obtener_tema()

        # Header
        header = Gtk.HeaderBar()
        header.set_show_close_button(True)
        header.props.title = f"You are editing theme: {self.tema}"
        self.set_titlebar(header)

        # Layout vertical
        vbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=7)
        self.add(vbox)

        # Opción 2: BSPWM Border (Editable)
        hbox2 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
        label2 = Gtk.Label()
        label2.set_xalign(0)  # Alinear a la izquierda
        label2.set_markup('Bspwm Border <i><small>(0-9)</small></i>')
        hbox2.pack_start(label2, True, True, 0)
        self.entry_border_width = Gtk.Entry()
        self.entry_border_width.set_text(self.obtener_border_width())
        self.entry_border_width.set_max_length(2)  # Limitar a 2 caracteres
        self.entry_border_width.set_input_purpose(Gtk.InputPurpose.NUMBER)
        hbox2.pack_end(self.entry_border_width, False, False, 0)
        btn_aplicar = Gtk.Button(label="Apply")
        btn_aplicar.connect("clicked", self.on_aplicar_clicked)
        hbox2.pack_end(btn_aplicar, False, False, 10)
        vbox.pack_start(hbox2, False, False, 0)

        # Nueva Opción: Bspwm Normal Border Color
        hbox_normal_bc = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
        label_normal_bc = Gtk.Label(label="Bspwm Normal Border Color")
        label_normal_bc.set_xalign(0)
        hbox_normal_bc.pack_start(label_normal_bc, True, True, 0)
        self.entry_normal_bc = Gtk.Entry()
        self.entry_normal_bc.set_text(self.obtener_normal_bc())
        self.entry_normal_bc.set_max_length(7)  # Limitar a 7 caracteres
        hbox_normal_bc.pack_end(self.entry_normal_bc, False, False, 0)
        btn_aplicar_normal_bc = Gtk.Button(label="Apply")
        btn_aplicar_normal_bc.connect("clicked", self.on_aplicar_normal_bc_clicked)
        hbox_normal_bc.pack_end(btn_aplicar_normal_bc, False, False, 10)
        vbox.pack_start(hbox_normal_bc, False, False, 0)

        # Nueva Opción: Bspwm Focused Border Color
        hbox_focused_bc = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
        label_focused_bc = Gtk.Label(label="Bspwm Focused Border Color")
        label_focused_bc.set_xalign(0)
        hbox_focused_bc.pack_start(label_focused_bc, True, True, 0)
        self.entry_focused_bc = Gtk.Entry()
        self.entry_focused_bc.set_text(self.obtener_focused_bc())
        self.entry_focused_bc.set_max_length(7)  # Limitar a 7 caracteres
        hbox_focused_bc.pack_end(self.entry_focused_bc, False, False, 0)
        btn_aplicar_focused_bc = Gtk.Button(label="Apply")
        btn_aplicar_focused_bc.connect("clicked", self.on_aplicar_focused_bc_clicked)
        hbox_focused_bc.pack_end(btn_aplicar_focused_bc, False, False, 10)
        vbox.pack_start(hbox_focused_bc, False, False, 0)

        # Nueva Opción: Bspwm Window Gap (Editable)
        hbox_window_gap = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
        label_window_gap = Gtk.Label()
        label_window_gap.set_xalign(0)
        label_window_gap.set_markup('*Bspwm Window Gap <i><small>(0-15)</small></i>')
        hbox_window_gap.pack_start(label_window_gap, True, True, 0)
        self.entry_window_gap = Gtk.Entry()
        self.entry_window_gap.set_text(self.obtener_window_gap())
        self.entry_window_gap.set_max_length(2)  # Limitar a 2 caracteres (0-15)
        self.entry_window_gap.set_input_purpose(Gtk.InputPurpose.NUMBER)
        hbox_window_gap.pack_end(self.entry_window_gap, False, False, 0)
        btn_aplicar_window_gap = Gtk.Button(label="Apply")
        btn_aplicar_window_gap.connect("clicked", self.on_aplicar_window_gap_clicked)
        hbox_window_gap.pack_end(btn_aplicar_window_gap, False, False, 10)
        vbox.pack_start(hbox_window_gap, False, False, 0)

        # Espacio en blanco
        vbox.pack_start(Gtk.Separator(), False, False, 10)

        # Opción 1: Activar animaciones (Switch)
        hbox1 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
        label1 = Gtk.Label(label="Picom Animations")
        label1.set_xalign(0)  # Alinear a la izquierda
        hbox1.pack_start(label1, True, True, 0)
        self.switch_animaciones = Gtk.Switch()
        self.switch_animaciones.set_active(self.obtener_estado_animaciones())
        hbox1.pack_end(self.switch_animaciones, False, False, 0)
        self.switch_animaciones.connect("notify::active", self.on_switch_activated)
        vbox.pack_start(hbox1, False, False, 0)

        # Opción 3: Picom Shadows (Switch)
        hbox3 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
        label3 = Gtk.Label(label="Picom Shadows")
        label3.set_xalign(0)  # Alinear a la izquierda
        hbox3.pack_start(label3, True, True, 0)
        self.switch_picom_shadows = Gtk.Switch()
        self.switch_picom_shadows.set_active(self.obtener_estado_picom_shadows())
        hbox3.pack_end(self.switch_picom_shadows, False, False, 0)
        self.switch_picom_shadows.connect("notify::active", self.on_switch_picom_shadows_activated)
        vbox.pack_start(hbox3, False, False, 0)

        # Opción 4: Shadow Color (Editable)
        hbox4 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
        label4 = Gtk.Label(label="Picom Shadow Color")
        label4.set_xalign(0)  # Alinear a la izquierda
        hbox4.pack_start(label4, True, True, 0)
        self.entry_shadow_color = Gtk.Entry()
        self.entry_shadow_color.set_text(self.obtener_shadow_color())
        self.entry_shadow_color.set_max_length(7)  # Limitar a 7 caracteres
        hbox4.pack_end(self.entry_shadow_color, False, False, 0)
        btn_aplicar_color = Gtk.Button(label="Apply")
        btn_aplicar_color.connect("clicked", self.on_aplicar_shadow_color_clicked)
        hbox4.pack_end(btn_aplicar_color, False, False, 10)
        vbox.pack_start(hbox4, False, False, 0)

        # Opción 5: Picom Fading (Switch)
        hbox5 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
        label5 = Gtk.Label(label="Picom Fading")
        label5.set_xalign(0)  # Alinear a la izquierda
        hbox5.pack_start(label5, True, True, 0)
        self.switch_picom_fading = Gtk.Switch()
        self.switch_picom_fading.set_active(self.obtener_estado_picom_fading())
        hbox5.pack_end(self.switch_picom_fading, False, False, 0)
        self.switch_picom_fading.connect("notify::active", self.on_switch_picom_fading_activated)
        vbox.pack_start(hbox5, False, False, 0)

        # Opción 6: Corner Radius (Editable)
        hbox6 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
        label6 = Gtk.Label(label="Picom Corner Radius")
        label6.set_xalign(0)  # Alinear a la izquierda
        hbox6.pack_start(label6, True, True, 0)
        self.entry_corner_radius = Gtk.Entry()
        self.entry_corner_radius.set_text(self.obtener_corner_radius())
        self.entry_corner_radius.set_max_length(2)  # Limitar a 2 dígitos numéricos
        self.entry_corner_radius.set_input_purpose(Gtk.InputPurpose.NUMBER)
        hbox6.pack_end(self.entry_corner_radius, False, False, 0)
        btn_aplicar_radius = Gtk.Button(label="Apply")
        btn_aplicar_radius.connect("clicked", self.on_aplicar_corner_radius_clicked)
        hbox6.pack_end(btn_aplicar_radius, False, False, 10)
        vbox.pack_start(hbox6, False, False, 0)

        # Espacio en blanco
        vbox.pack_start(Gtk.Separator(), False, False, 10)

        # Nueva opción: Backend (ComboBox)
        hbox_backend = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
        label_backend = Gtk.Label(label="*Backend")
        label_backend.set_xalign(0)
        hbox_backend.pack_start(label_backend, True, True, 0)
        self.combo_backend = Gtk.ComboBoxText()
        self.combo_backend.append_text("xrender")
        self.combo_backend.append_text("glx")
        self.combo_backend.append_text("egl")
        self.combo_backend.set_active(self.obtener_estado_backend())  # Establecer el backend actual
        hbox_backend.pack_end(self.combo_backend, False, False, 0)
        self.combo_backend.connect("changed", self.on_backend_changed)
        vbox.pack_start(hbox_backend, False, False, 0)

        # Nueva opción: VSync (Switch)
        hbox_vsync = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
        label_vsync = Gtk.Label(label="*vSync")
        label_vsync.set_xalign(0)
        hbox_vsync.pack_start(label_vsync, True, True, 0)
        self.switch_vsync = Gtk.Switch()
        self.switch_vsync.set_active(self.obtener_estado_vsync())
        hbox_vsync.pack_end(self.switch_vsync, False, False, 0)
        self.switch_vsync.connect("notify::active", self.on_switch_vsync_activated)
        vbox.pack_start(hbox_vsync, False, False, 0)

        # Espacio en blanco
        vbox.pack_start(Gtk.Separator(), False, False, 10)

        # Nueva opción: Pixel-art on terminal startup (Switch)
        hbox_pixelart = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
        label_pixelart = Gtk.Label(label="*Pixel-art on terminal startup")
        label_pixelart.set_xalign(0)
        hbox_pixelart.pack_start(label_pixelart, True, True, 0)
        self.switch_pixelart = Gtk.Switch()
        self.switch_pixelart.set_active(self.obtener_estado_pixelart())
        hbox_pixelart.pack_end(self.switch_pixelart, False, False, 0)
        self.switch_pixelart.connect("notify::active", self.on_switch_pixelart_activated)
        vbox.pack_start(hbox_pixelart, False, False, 0)

        espacio_vacio = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL)
        vbox.pack_start(espacio_vacio, False, False, 5)

        # Botón Reset to defaults
        btn_reset_defaults = Gtk.Button(label="Reset to defaults")
        btn_reset_defaults.connect("clicked", lambda w: self.reset_to_defaults())
        vbox.pack_start(btn_reset_defaults, False, False, 0)

        espacio_vacio = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL)
        vbox.pack_start(espacio_vacio, False, False, 5)

        # (*) Global options info
        label_global_options = Gtk.Label()
        label_global_options.set_markup('<i><small>(*) Global options. They do not depend on the theme you are in.</small></i>')
        vbox.pack_end(label_global_options, False, False, 0)

    def set_fuente_personalizada(self):
        css = """
        * {
            font-family: 'JetBrainsMono Nerd Font';
            font-size: 13px;
        }
        """
        css_provider = Gtk.CssProvider()
        css_provider.load_from_data(css.encode('utf-8'))
        Gtk.StyleContext.add_provider_for_screen(
            Gdk.Screen.get_default(),
            css_provider,
            Gtk.STYLE_PROVIDER_PRIORITY_USER
        )

    def reset_to_defaults(self):
		# Restablecer window_gap a 5 (opción global)
        self.modificar_bspwmrc("window_gap", "5")
        subprocess.run(["bspc", "config", "window_gap", "5"], check=True)
        print("Window gap reset to default value (5).")

        # Restablecer las opciones del tema según el tema actual
        tema = self.tema
        defaults = {
            "aline": {
                "BORDER_WIDTH": "0",
                "P_SHADOWS": "true",
                "P_CORNER_R": "6",
                "SHADOW_C": "#000000",
                "ANIMATIONS": "true",
                "P_FADE": "true",
                "NORMAL_BC": "#286983",
                "FOCUSED_BC": "#907aa9"
            },
            "andrea": {
                "BORDER_WIDTH": "0",
                "P_SHADOWS": "true",
                "P_CORNER_R": "6",
                "SHADOW_C": "#000000",
                "ANIMATIONS": "true",
                "P_FADE": "true",
                "NORMAL_BC": "#16161C",
                "FOCUSED_BC": "#b0a5ed"
            },
            "brenda": {
                "BORDER_WIDTH": "0",
                "P_SHADOWS": "true",
                "P_CORNER_R": "6",
                "SHADOW_C": "#000000",
                "ANIMATIONS": "true",
                "P_FADE": "true",
                "NORMAL_BC": "#d3c6aa",
                "FOCUSED_BC": "#a7c080"
            },
            "cristina": {
                "BORDER_WIDTH": "0",
                "P_SHADOWS": "true",
                "P_CORNER_R": "6",
                "SHADOW_C": "#000000",
                "ANIMATIONS": "true",
                "P_FADE": "true",
                "NORMAL_BC": "#9bced7",
                "FOCUSED_BC": "#c3a5e6"
            },
            "cynthia": {
                "BORDER_WIDTH": "0",
                "P_SHADOWS": "true",
                "P_CORNER_R": "6",
                "SHADOW_C": "#000000",
                "ANIMATIONS": "true",
                "P_FADE": "true",
                "NORMAL_BC": "#0d0c0c",
                "FOCUSED_BC": "#938AA9"
            },
            "daniela": {
                "BORDER_WIDTH": "0",
                "P_SHADOWS": "true",
                "P_CORNER_R": "6",
                "SHADOW_C": "#000000",
                "ANIMATIONS": "true",
                "P_FADE": "true",
                "NORMAL_BC": "#45475A",
                "FOCUSED_BC": "#94E2D5"
            },
            "emilia": {
                "BORDER_WIDTH": "0",
                "P_SHADOWS": "true",
                "P_CORNER_R": "6",
                "SHADOW_C": "#000000",
                "ANIMATIONS": "true",
                "P_FADE": "true",
                "NORMAL_BC": "#414868",
                "FOCUSED_BC": "#bb9af7"
            },
            "h4ck3r": {
                "BORDER_WIDTH": "0",
                "P_SHADOWS": "false",
                "P_CORNER_R": "0",
                "SHADOW_C": "#000000",
                "ANIMATIONS": "false",
                "P_FADE": "false",
                "NORMAL_BC": "#4A9801",
                "FOCUSED_BC": "#76EA00"
            },
            "isabel": {
                "BORDER_WIDTH": "0",
                "P_SHADOWS": "true",
                "P_CORNER_R": "6",
                "SHADOW_C": "#000000",
                "ANIMATIONS": "true",
                "P_FADE": "true",
                "NORMAL_BC": "#b8bfe5",
                "FOCUSED_BC": "#7560d3"
            },
            "jan": {
                "BORDER_WIDTH": "0",
                "P_SHADOWS": "false",
                "P_CORNER_R": "0",
                "SHADOW_C": "#000000",
                "ANIMATIONS": "true",
                "P_FADE": "true",
                "NORMAL_BC": "#926BCA",
                "FOCUSED_BC": "#fb007a"
            },
            "karla": {
                "BORDER_WIDTH": "3",
                "P_SHADOWS": "false",
                "P_CORNER_R": "0",
                "SHADOW_C": "#000000",
                "ANIMATIONS": "true",
                "P_FADE": "false",
                "NORMAL_BC": "#353c52",
                "FOCUSED_BC": "#353c52"
            },
            "marisol": {
                "BORDER_WIDTH": "2",
                "P_SHADOWS": "false",
                "P_CORNER_R": "0",
                "SHADOW_C": "#000000",
                "ANIMATIONS": "true",
                "P_FADE": "true",
                "NORMAL_BC": "#ff79c6",
                "FOCUSED_BC": "#bd93f9"
            },
            "melissa": {
                "BORDER_WIDTH": "0",
                "P_SHADOWS": "true",
                "P_CORNER_R": "6",
                "SHADOW_C": "#000000",
                "ANIMATIONS": "true",
                "P_FADE": "true",
                "NORMAL_BC": "#3b4252",
                "FOCUSED_BC": "#4c566a"
            },
            "pamela": {
                "BORDER_WIDTH": "0",
                "P_SHADOWS": "true",
                "P_CORNER_R": "6",
                "SHADOW_C": "#000000",
                "ANIMATIONS": "true",
                "P_FADE": "true",
                "NORMAL_BC": "#C574DD",
                "FOCUSED_BC": "#8897F4"
            },
            "silvia": {
                "BORDER_WIDTH": "0",
                "P_SHADOWS": "true",
                "P_CORNER_R": "6",
                "SHADOW_C": "#000000",
                "ANIMATIONS": "true",
                "P_FADE": "true",
                "NORMAL_BC": "#d3869b",
                "FOCUSED_BC": "#fbf1c7"
            },
            "varinka": {
                "BORDER_WIDTH": "0",
                "P_SHADOWS": "true",
                "P_CORNER_R": "6",
                "SHADOW_C": "#000000",
                "ANIMATIONS": "true",
                "P_FADE": "true",
                "NORMAL_BC": "#ced4da",
                "FOCUSED_BC": "#f8f9fa"
            },
            "yael": {
                "BORDER_WIDTH": "0",
                "P_SHADOWS": "true",
                "P_CORNER_R": "6",
                "SHADOW_C": "#000000",
                "ANIMATIONS": "true",
                "P_FADE": "true",
                "NORMAL_BC": "#33b1ff",
                "FOCUSED_BC": "#42be65"
            },
            "z0mbi3": {
                "BORDER_WIDTH": "0",
                "P_SHADOWS": "true",
                "P_CORNER_R": "6",
                "SHADOW_C": "#000000",
                "ANIMATIONS": "true",
                "P_FADE": "true",
                "NORMAL_BC": "#3d414f",
                "FOCUSED_BC": "#93cee9"
            }
        }

        if tema in defaults:
            valores_default = defaults[tema]

            # Apply default values ​​to variables in Theme.sh
            self.modificar_archivo_tema("BORDER_WIDTH", valores_default["BORDER_WIDTH"])
            self.modificar_archivo_tema("P_SHADOWS", valores_default["P_SHADOWS"])
            self.modificar_archivo_tema("P_CORNER_R", valores_default["P_CORNER_R"])
            self.modificar_archivo_tema("SHADOW_C", valores_default["SHADOW_C"])
            self.modificar_archivo_tema("ANIMATIONS", valores_default["ANIMATIONS"])
            self.modificar_archivo_tema("P_FADE", valores_default["P_FADE"])
            self.modificar_archivo_tema("NORMAL_BC", valores_default["NORMAL_BC"])
            self.modificar_archivo_tema("FOCUSED_BC", valores_default["FOCUSED_BC"])

            # Apply changes in real time
            subprocess.run(["bspc", "config", "border_width", valores_default["BORDER_WIDTH"]], check=True)
            subprocess.run(["bspc", "config", "normal_border_color", valores_default["NORMAL_BC"]], check=True)
            subprocess.run(["bspc", "config", "focused_border_color", valores_default["FOCUSED_BC"]], check=True)
            self.modificar_config_picom_shadows(valores_default["P_SHADOWS"] == "true")
            self.modificar_config_picom_color_sombra(valores_default["SHADOW_C"])
            self.modificar_config_picom_corner_radius(valores_default["P_CORNER_R"])
            self.modificar_config_picom_fading(valores_default["P_FADE"] == "true")

            # Update fields in the interface
            self.entry_border_width.set_text(valores_default["BORDER_WIDTH"])
            self.switch_picom_shadows.set_active(valores_default["P_SHADOWS"] == "true")
            self.entry_corner_radius.set_text(valores_default["P_CORNER_R"])
            self.entry_shadow_color.set_text(valores_default["SHADOW_C"])
            self.switch_animaciones.set_active(valores_default["ANIMATIONS"] == "true")
            self.switch_picom_fading.set_active(valores_default["P_FADE"] == "true")
            self.entry_normal_bc.set_text(valores_default["NORMAL_BC"])
            self.entry_focused_bc.set_text(valores_default["FOCUSED_BC"])
            self.entry_window_gap.set_text("5")

            print(f"Restored default values ​​for the theme: {tema}")
        else:
            print(f"There are no default values ​​configured for the theme: {tema}")

    def obtener_tema(self):
        try:
            ruta_tema = os.path.expanduser("~/.config/bspwm/.rice")
            with open(ruta_tema, "r") as archivo:
                tema = archivo.readline().strip()
            return tema
        except FileNotFoundError:
            return "Desconocido"
        except Exception as e:
            return f"Error: {str(e)}"

    def obtener_estado_animaciones(self):
        return self.obtener_estado_variable("ANIMATIONS")

    def obtener_border_width(self):
        return self.obtener_valor_variable("BORDER_WIDTH")

    def obtener_estado_picom_shadows(self):
        return self.obtener_estado_variable("P_SHADOWS")

    def obtener_shadow_color(self):
        return self.obtener_valor_variable("SHADOW_C")

    def obtener_estado_picom_fading(self):
        return self.obtener_estado_variable("P_FADE")

    def obtener_corner_radius(self):
        return self.obtener_valor_variable("P_CORNER_R")

    def obtener_normal_bc(self):
        return self.obtener_valor_variable("NORMAL_BC")

    def obtener_focused_bc(self):
        return self.obtener_valor_variable("FOCUSED_BC")

    def obtener_estado_vsync(self):
        # Leer el valor de vsync desde el archivo picom.conf
        ruta_picom = os.path.expanduser("~/.config/bspwm/src/config/picom.conf")
        with open(ruta_picom, "r") as archivo:
            for linea in archivo:
                if re.search(r'vsync\s*=\s*(true|false)', linea):
                    return 'true' in linea
        return False

    def obtener_estado_backend(self):
        ruta_picom = os.path.expanduser("~/.config/bspwm/src/config/picom.conf")
        with open(ruta_picom, "r") as archivo:
            for linea in archivo:
                match = re.search(r'backend\s*=\s*"(xrender|glx|egl)"', linea)
                if match:
                    backend = match.group(1)
                    if backend == "xrender":
                        return 0
                    elif backend == "glx":
                        return 1
                    elif backend == "egl":
                        return 2
        return 0  # Valor predeterminado si no se encuentra

    def obtener_estado_pixelart(self):
        # Leer el estado de pixel art en el archivo .zshrc
        ruta_zshrc = os.path.expanduser("~/.zshrc")
        with open(ruta_zshrc, "r") as archivo:
            for linea in archivo:
                if re.search(r'^\s*\$HOME/.local/bin/colorscript -r', linea):
                    return True
        return False

    def obtener_estado_variable(self, variable):
        try:
            ruta_script = os.path.expanduser(f"~/.config/bspwm/rices/{self.tema}/Theme.sh")
            with open(ruta_script, "r") as archivo:
                contenido = archivo.read()
            estado = re.search(rf'{variable}="(true|false)"', contenido)
            if estado:
                return estado.group(1) == "true"
        except Exception as e:
            print(f"Error reading theme file: {str(e)}")
        return False

    def obtener_valor_variable(self, variable):
        try:
            ruta_script = os.path.expanduser(f"~/.config/bspwm/rices/{self.tema}/Theme.sh")
            with open(ruta_script, "r") as archivo:
                contenido = archivo.read()
            valor = re.search(rf'{variable}="([^"]+)"', contenido)
            if valor:
                return valor.group(1)
        except Exception as e:
            print(f"Error reading theme file: {str(e)}")
        return "0"

    def on_switch_activated(self, switch, gparam):
        nuevo_estado = "true" if switch.get_active() else "false"
        self.modificar_archivo_tema("ANIMATIONS", nuevo_estado)
        self.modificar_config_picom(switch.get_active())

    def on_aplicar_clicked(self, button):
        valor_borde = self.entry_border_width.get_text()
        if not valor_borde.isdigit() or not (0 <= int(valor_borde) <= 10):
            print("Invalid value for border. It must be a number between 0 and 10.")
            return
        self.modificar_archivo_tema("BORDER_WIDTH", valor_borde)
        try:
            subprocess.run(["bspc", "config", "border_width", valor_borde], check=True)
            print(f"Border changed to: {valor_borde}")
        except Exception as e:
            print(f"Error applying border: {str(e)}")

    def on_switch_picom_shadows_activated(self, switch, gparam):
        nuevo_estado = "true" if switch.get_active() else "false"
        self.modificar_archivo_tema("P_SHADOWS", nuevo_estado)
        self.modificar_config_picom_shadows(switch.get_active())

    def on_aplicar_shadow_color_clicked(self, button):
        color_valido = self.entry_shadow_color.get_text()
        if not re.match(r'^#[0-9A-Fa-f]{6}$', color_valido):
            print("Invalid color. It must be a hexadecimal value in the format #000000.")
            return
        self.modificar_archivo_tema("SHADOW_C", color_valido)
        self.modificar_config_picom_color_sombra(color_valido)

    def on_aplicar_normal_bc_clicked(self, button):
        color_valido = self.entry_normal_bc.get_text()
        if not re.match(r'^#[0-9A-Fa-f]{6}$', color_valido):
            print("Invalid color. It must be a hexadecimal value in the format #000000.")
            return
        self.modificar_archivo_tema("NORMAL_BC", color_valido)
        subprocess.run(["bspc", "config", "normal_border_color", color_valido], check=True)
        print(f"Normal border color changed to: {color_valido}")

    def on_aplicar_focused_bc_clicked(self, button):
        color_valido = self.entry_focused_bc.get_text()
        if not re.match(r'^#[0-9A-Fa-f]{6}$', color_valido):
            print("Invalid color. It must be a hexadecimal value in the format #000000.")
            return
        self.modificar_archivo_tema("FOCUSED_BC", color_valido)
        subprocess.run(["bspc", "config", "focused_border_color", color_valido], check=True)
        print(f"Focused border color changed to: {color_valido}")

    def on_aplicar_window_gap_clicked(self, button):
        gap_valido = self.entry_window_gap.get_text()
        if not re.match(r'^[0-9]{1,2}$', gap_valido) or not (0 <= int(gap_valido) <= 15):
            print("Invalid gap value. It must be a number between 0 and 15.")
            return
        self.modificar_bspwmrc("window_gap", gap_valido)
        subprocess.run(["bspc", "config", "window_gap", gap_valido], check=True)
        print(f"Window gap changed to: {gap_valido}")

    def obtener_window_gap(self):
        # Leer el valor de window_gap desde el archivo bspwmrc
        ruta_bspwmrc = os.path.expanduser("~/.config/bspwm/bspwmrc")
        with open(ruta_bspwmrc, "r") as archivo:
            for linea in archivo:
                match = re.search(r'\bwindow_gap\s+(\d+)', linea)
                if match:
                    return match.group(1)
        return "5"  # Valor predeterminado si no se encuentra

    def modificar_bspwmrc(self, opcion, valor):
        # Modificar el valor de window_gap en el archivo bspwmrc
        ruta_bspwmrc = os.path.expanduser("~/.config/bspwm/bspwmrc")
        with open(ruta_bspwmrc, "r") as archivo:
            contenido = archivo.readlines()

        for i, linea in enumerate(contenido):
            if re.search(rf'\b{opcion}\s+\d+', linea):
                contenido[i] = f'bspc config {opcion} {valor}\n'
                break

        with open(ruta_bspwmrc, "w") as archivo:
            archivo.writelines(contenido)

    def on_switch_picom_fading_activated(self, switch, gparam):
        nuevo_estado = "true" if switch.get_active() else "false"
        self.modificar_archivo_tema("P_FADE", nuevo_estado)
        self.modificar_config_picom_fading(switch.get_active())

    def on_aplicar_corner_radius_clicked(self, button):
        valor_radius = self.entry_corner_radius.get_text()
        if not valor_radius.isdigit() or not (0 <= int(valor_radius) <= 99):
            print("Invalid value for corner radius. It must be a number between 0 and 99.")
            return
        self.modificar_archivo_tema("P_CORNER_R", valor_radius)
        self.modificar_config_picom_corner_radius(valor_radius)

    def on_switch_vsync_activated(self, switch, gparam):
        estado_vsync = switch.get_active()
        ruta_picom = os.path.expanduser("~/.config/bspwm/src/config/picom.conf")
        with open(ruta_picom, "r") as archivo:
            contenido = archivo.readlines()

        # Modificar la línea vsync = true o false
        for i, linea in enumerate(contenido):
            if re.search(r'vsync\s*=\s*(true|false)', linea):
                contenido[i] = f'vsync = {"true" if estado_vsync else "false"};\n'
                break

        with open(ruta_picom, "w") as archivo:
            archivo.writelines(contenido)

        print(f"VSync {'enabled' if estado_vsync else 'disabled'} in picom.conf")

    def on_backend_changed(self, combo):
        backend_seleccionado = combo.get_active_text()
        ruta_picom = os.path.expanduser("~/.config/bspwm/src/config/picom.conf")
        with open(ruta_picom, "r") as archivo:
            contenido = archivo.readlines()

        # Modificar la línea backend = "xrender"
        for i, linea in enumerate(contenido):
            if re.search(r'backend\s*=\s*"(xrender|glx|egl)"', linea):
                contenido[i] = f'backend = "{backend_seleccionado}"\n'
                break

        with open(ruta_picom, "w") as archivo:
            archivo.writelines(contenido)

        print(f"Backend changed to {backend_seleccionado} in picom.conf")

    def on_switch_pixelart_activated(self, switch, gparam):
        estado_pixelart = switch.get_active()
        ruta_zshrc = os.path.expanduser("~/.zshrc")

        try:
            # Leer el contenido del archivo .zshrc
            with open(ruta_zshrc, "r") as archivo:
                contenido = archivo.readlines()

            # Modificar la línea $HOME/.local/bin/colorscript -r
            linea_modificada = False
            for i, linea in enumerate(contenido):
                # Buscar la línea con o sin comentario
                if re.search(r'^\s*\$HOME/.local/bin/colorscript -r', linea) or re.search(r'^\s*#\s*\$HOME/.local/bin/colorscript -r', linea):
                    if estado_pixelart:
                        contenido[i] = '$HOME/.local/bin/colorscript -r\n'  # Activar la línea
                    else:
                        contenido[i] = '#$HOME/.local/bin/colorscript -r\n'  # Desactivar la línea
                    linea_modificada = True
                    break

            if linea_modificada:
                # Guardar los cambios en .zshrc
                with open(ruta_zshrc, "w") as archivo:
                    archivo.writelines(contenido)
                print(f"Pixel-art on terminal startup {'enabled' if estado_pixelart else 'disabled'} in .zshrc")
            else:
                print("No se encontró la línea correspondiente en el archivo .zshrc")

        except Exception as e:
            print(f"Error al modificar .zshrc: {str(e)}")

    def modificar_archivo_tema(self, variable, nuevo_valor):
        try:
            ruta_script = os.path.expanduser(f"~/.config/bspwm/rices/{self.tema}/Theme.sh")
            with open(ruta_script, "r") as archivo:
                contenido = archivo.read()
            nuevo_contenido = re.sub(rf'{variable}="[^"]+"', f'{variable}="{nuevo_valor}"', contenido)
            with open(ruta_script, "w") as archivo:
                archivo.write(nuevo_contenido)
            print(f"{variable} changed to: {nuevo_valor}")
        except Exception as e:
            print(f"Error modifying theme file: {str(e)}")

    def modificar_config_picom(self, activar_animaciones):
        try:
            # Modificar picom-rules.conf para @include "picom-animations.conf"
            ruta_picom_rules = os.path.expanduser("~/.config/bspwm/src/config/picom-rules.conf")
            with open(ruta_picom_rules, "r") as archivo:
                contenido_rules = archivo.readlines()

            nueva_linea = '@include "picom-animations.conf"\n'
            for i, linea in enumerate(contenido_rules):
                if 'picom-animations.conf' in linea:
                    if activar_animaciones:
                        contenido_rules[i] = nueva_linea
                    else:
                        contenido_rules[i] = f"#{nueva_linea}"
                    break

            with open(ruta_picom_rules, "w") as archivo:
                archivo.writelines(contenido_rules)

            print("Modified Picom configuration.")
        except Exception as e:
            print(f"Error modifying Picom file: {str(e)}")

    def modificar_config_picom_shadows(self, activar_sombras):
        try:
            ruta_picom = os.path.expanduser("~/.config/bspwm/src/config/picom.conf")
            with open(ruta_picom, "r") as archivo:
                contenido = archivo.readlines()
            nueva_linea = 'shadow = true;\n' if activar_sombras else 'shadow = false;\n'
            for i, linea in enumerate(contenido):
                if 'shadow =' in linea:
                    contenido[i] = nueva_linea
                    break
            with open(ruta_picom, "w") as archivo:
                archivo.writelines(contenido)
            print("Modified Picom Shadows.")
        except Exception as e:
            print(f"Error when modifying shadows in Picom: {str(e)}")

    def modificar_config_picom_color_sombra(self, nuevo_valor):
        try:
            ruta_picom = os.path.expanduser("~/.config/bspwm/src/config/picom.conf")
            with open(ruta_picom, "r") as archivo:
                contenido = archivo.read()
            contenido_modificado = re.sub(r'shadow-color = "#.*?"', f'shadow-color = "{nuevo_valor}"', contenido)
            with open(ruta_picom, "w") as archivo:
                archivo.write(contenido_modificado)
            print(f"Shadow color modified to: {nuevo_valor}")
        except Exception as e:
            print(f"Error when modifying shadow color in Picom: {str(e)}")

    def modificar_config_picom_corner_radius(self, nuevo_valor):
        try:
            ruta_picom = os.path.expanduser("~/.config/bspwm/src/config/picom.conf")
            with open(ruta_picom, "r") as archivo:
                contenido = archivo.read()
            contenido_modificado = re.sub(r'corner-radius = \d+', f'corner-radius = {nuevo_valor}', contenido)
            with open(ruta_picom, "w") as archivo:
                archivo.write(contenido_modificado)
            print(f"Corner radius modified to: {nuevo_valor}")
        except Exception as e:
            print(f"Error when modifying the corner radius in Picom: {str(e)}")

    def modificar_config_picom_fading(self, activar_fading):
        try:
            ruta_picom = os.path.expanduser("~/.config/bspwm/src/config/picom.conf")
            with open(ruta_picom, "r") as archivo:
                contenido = archivo.readlines()
            nueva_linea = 'fading = true;\n' if activar_fading else 'fading = false;\n'
            for i, linea in enumerate(contenido):
                if 'fading =' in linea:
                    contenido[i] = nueva_linea
                    break
            with open(ruta_picom, "w") as archivo:
                archivo.writelines(contenido)
            print("Fading modified.")
        except Exception as e:
            print(f"Error when modifying the fading in Picom: {str(e)}")

win = ConfigurarTemaWindow()
win.connect("destroy", Gtk.main_quit)
win.show_all()

# Iniciar el loop principal de GTK
Gtk.main()
