#!/bin/sh
# =============================================================
# Author: gh0stzk
# Repo:   https://github.com/gh0stzk/dotfiles
# Date:   27.06.2025 12:30:38
#
# Script Name: RofiLauncher
# Description: Dynamic theme selector and launcher for Rofi
#
# Copyright (C) 2021-2025 gh0stzk <z0mbi3.zk@protonmail.com>
# Licensed under GPL-3.0 license
# =============================================================

# Main vars
cfgStyle="$HOME/.config/bspwm/src/config/.launcher"
[ -f "$cfgStyle" ] || echo "1" > "$cfgStyle"
read -r current_style < "$cfgStyle"

# Paths
styleDir="$HOME/.config/bspwm/src/rofi-themes"
rofiAssetDir="$HOME/.config/bspwm/src/assets"

# Function to select the styles
choose_launcher_style() {

    # Find styles
    styles=$(find "$styleDir" -type f -name 'style_*.rasi' | sed 's|.*/style_\([0-9]*\)\.rasi|\1|' | sort -n)

    # Find current style
    selected_index=-1
    index=0
    IFS='
'
    for style in $styles; do
        if [ "$style" = "$current_style" ]; then
            selected_index=$index
            break
        fi
        index=$((index + 1))
    done
    unset IFS

    # Show the rofi selection menu
    selected=$(
    IFS='
'
    for style in $styles; do
        printf "%s\000icon\037%s/style_%s.webp\n" "$style" "$rofiAssetDir" "$style"
    done | rofi -dmenu \
                -theme "$HOME/.config/bspwm/src/rofi-themes/StyleSelect.rasi" \
                -selected-row "$selected_index"
    )

    # Write the selection to config file
    [ -n "$selected" ] && echo "${selected}" > "$cfgStyle"

}

launch_launcher () {
    ROFI_THEME="$HOME/.config/bspwm/src/rofi-themes/style_$current_style.rasi"
    rofi -show drun -theme "$ROFI_THEME"
}

# -- Main executor -- #
case "$1" in
    --choose-style)
        choose_launcher_style ;;
    --launcher | *)
        launch_launcher ;;
esac
