#!/bin/sh
# =============================================================
# Author: gh0stzk
# Repo:   https://github.com/gh0stzk/dotfiles
# Date:   25.04.2025 07:43:03
#
# Script Name: RofiLauncher
# Description: Dynamic theme selector and launcher for Rofi
# Features:
#   - DPI-aware icon sizing
#   - Multi-style theme selection
#   - Persistent style configuration
#
# Copyright (C) 2021-2025 gh0stzk <z0mbi3.zk@protonmail.com>
# Licensed under GPL-3.0 license
# =============================================================

# Main vars
cfgStyle="$HOME/.config/bspwm/src/config/.launcher"
[ -f "$cfgStyle" ] || echo "1" > "$cfgStyle"
read -r current_style < "$cfgStyle"

# Paths
styleDir="$HOME/.config/bspwm/src/rofi-themes"
rofiAssetDir="$HOME/.config/bspwm/src/assets"

# Get focused monitor name
focused_monitor=$(bspc query -M -m focused --names)

# Get monitor width and DPI
monitor_width=$(xrandr | grep -w -- "$focused_monitor" | grep -o '[0-9]\+x[0-9]\+' | cut -d 'x' -f 1)
screen_dpi=$(xdpyinfo | awk '/resolution/{print $2; exit}' | cut -d 'x' -f1)

# Calculate icon size
icon_size=$(( (monitor_width * 11) / (${screen_dpi:-96} ) ))
rofi_override="element-icon{size:${icon_size}px;}"

# Function to select the styles
choose_launcher_style() {

    # Find styles
    styles=$(find "$styleDir" -type f -name 'style_*.rasi' | sed 's|.*/style_\([0-9]*\)\.rasi|\1|' | sort -n)

    # Find current style
    selected_index=-1
    index=0
    IFS='
'
    for style in $styles; do
        if [ "$style" = "$current_style" ]; then
            selected_index=$index
            break
        fi
        index=$((index + 1))
    done
    unset IFS

    # Show the rofi selection menu
    selected=$(
    IFS='
'
    for style in $styles; do
        printf "%s\000icon\037%s/style_%s.webp\n" "$style" "$rofiAssetDir" "$style"
    done | rofi -dmenu \
                -theme "$HOME/.config/bspwm/src/rofi-themes/StyleSelect.rasi" \
                -theme-str "$rofi_override" \
                -selected-row "$selected_index"
    )

    # Write the selection to config file
    [ -n "$selected" ] && echo "${selected}" > "$cfgStyle"

}

launch_launcher () {
    ROFI_THEME="$HOME/.config/bspwm/src/rofi-themes/style_$current_style.rasi"
    rofi -show drun -theme "$ROFI_THEME"
}

# -- Main executor -- #
case "$1" in
    --choose-style)
        choose_launcher_style ;;
    --launcher | *)
        launch_launcher ;;
esac
