#!/usr/bin/env bash
#  ███████╗██╗   ██╗███████╗████████╗███████╗███╗   ███╗    ██╗   ██╗ █████╗ ██████╗ ███████╗
#  ██╔════╝╚██╗ ██╔╝██╔════╝╚══██╔══╝██╔════╝████╗ ████║    ██║   ██║██╔══██╗██╔══██╗██╔════╝
#  ███████╗ ╚████╔╝ ███████╗   ██║   █████╗  ██╔████╔██║    ██║   ██║███████║██████╔╝███████╗
#  ╚════██║  ╚██╔╝  ╚════██║   ██║   ██╔══╝  ██║╚██╔╝██║    ╚██╗ ██╔╝██╔══██║██╔══██╗╚════██║
#  ███████║   ██║   ███████║   ██║   ███████╗██║ ╚═╝ ██║     ╚████╔╝ ██║  ██║██║  ██║███████║
#  ╚══════╝   ╚═╝   ╚══════╝   ╚═╝   ╚══════╝╚═╝     ╚═╝      ╚═══╝  ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝
#	Author	-	gh0stzk
#	Repo	-	https://github.com/gh0stzk/dotfiles
#	date	-	02.02.2025 08:44:12

# SetSysVars - Automated System Configuration for BSPWM
# Features:
#   ✔ Sets up variables for Polybar integration.
#      * Sets up network interfaces
#      * Sets up graphics card
#      * Sets up power supply
#   ✔ Creates a lock file after first execution
#
# Dependencies:
#   → Core: awk, grep, sed, iproute2 (All in Arch base)
#
# Copyright (C) 2021-2025 gh0stzk <z0mbi3.zk@protonmail.com>
# Licensed under GPL-3.0 license


CONFIG_FILE="$HOME/.config/bspwm/src/config/system.ini"
SFILE="$HOME/.config/bspwm/src/.sys"

[[ -f "$SFILE" ]] && exit 0 # The file exists, exit without doing anything

# Wait for NetworkManager connection
until nmcli -t -f STATE general | grep -q 'connected'; do
    sleep 0.2
done

setup_system_vars() {
    # Primary Network Interface Detection
    local primary_net=$(ip route show default 2>/dev/null | awk '/default/ {print $5; exit}')

    # Graphics card detection
    local card=$(ls /sys/class/backlight/ 2>/dev/null | head -n1)

    # Battery and adapter detection
    local battery=$(ls /sys/class/power_supply/ 2>/dev/null | grep -m1 'BAT')
    local adapter=$(ls /sys/class/power_supply/ 2>/dev/null | grep -m1 -E 'AC|ADP')

    # Atomic update of the configuration file
    tmpfile=$(mktemp)
    awk -v net="$primary_net" \
        -v card="$card" \
        -v bat="$battery" \
        -v adap="$adapter" '
        /^sys_network_interface =/ {$0="sys_network_interface = " net}
        /^sys_graphics_card =/ {$0="sys_graphics_card = " card}
        /^sys_battery =/ {$0="sys_battery = " bat}
        /^sys_adapter =/ {$0="sys_adapter = " adap}
        {print}
    ' "$CONFIG_FILE" > "$tmpfile" && mv "$tmpfile" "$CONFIG_FILE"
}

# Main execution
setup_system_vars
touch "$SFILE"
