#!/usr/bin/env bash
#  ████████╗███████╗██████╗ ███╗   ███╗██╗███╗   ██╗ █████╗ ██╗     
#  ╚══██╔══╝██╔════╝██╔══██╗████╗ ████║██║████╗  ██║██╔══██╗██║     
#     ██║   █████╗  ██████╔╝██╔████╔██║██║██╔██╗ ██║███████║██║     
#     ██║   ██╔══╝  ██╔══██╗██║╚██╔╝██║██║██║╚██╗██║██╔══██║██║     
#     ██║   ███████╗██║  ██║██║ ╚═╝ ██║██║██║ ╚████║██║  ██║███████╗
#     ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝
#   Script to open with selected terminal
#   Author: z0mbi3
#   url: https://github.com/gh0stzk/dotfiles


cfg_term="$HOME/.config/bspwm/src/.term"

if [ ! -e "$cfg_term" ]; then
    echo alacritty >"$cfg_term"
fi

MY_TERM=$(<"$cfg_term")
export MY_TERM

# Function to choose the terminal using rofi
choose_terminal() {
    local options="Alacritty\nKitty"
    local chosen
    chosen=$(echo -e "$options" | rofi -theme "$HOME/.config/bspwm/src/rofi-themes/TermSelector.rasi" -dmenu)
    
    case $chosen in
        "Alacritty")
            echo alacritty >"$cfg_term"
            ;;
        "Kitty")
            echo kitty >"$cfg_term"
            ;;
    esac
}

if [[ "$1" == "--selecterm" ]]; then
    choose_terminal
fi

# Launch the terminal with appropriate options
case $MY_TERM in
    "alacritty")
        case $1 in
            "--terminal")
                alacritty
                ;;
            "--floating")
                alacritty --class FloaTerm,FloaTerm -o window.dimensions.lines=22 window.dimensions.columns=90
                ;;
            "--update")
                alacritty --hold --class FloaTerm,FloaTerm -o window.dimensions.lines=22 window.dimensions.columns=90 -e Updates --update-system
                ;;
            "--checkupdates")
                alacritty --hold --class Updating,Updating -o window.dimensions.lines=22 window.dimensions.columns=47 -e Updates --print-updates
                ;;
            "--ranger")
                alacritty --class FloaTerm,FloaTerm -o window.dimensions.lines=14 window.dimensions.columns=90 -e ranger
                ;;
            "--nvim")
                alacritty -e nvim
                ;;
            "--music")
                alacritty --class FloaTerm,FloaTerm -o window.dimensions.lines=18 window.dimensions.columns=67 -e ncmpcpp
                ;;
            "--fetch")
                alacritty --class FloaTerm,FloaTerm -o window.dimensions.lines=26 window.dimensions.columns=40 -e ~/.local/bin/sysfetch
                ;;
        esac
        ;;
    "kitty")
        case $1 in
            "--terminal")
                kitty
                ;;
            "--floating")
                kitty --class=FloaTerm -o initial_window_width=842 -o initial_window_height=495
                ;;
            "--update")
                kitty --hold --class=FloaTerm -o initial_window_width=842 -o initial_window_height=495 -e Updates --update-system
                ;;
            "--checkupdates")
                kitty --hold --class=Updating -o initial_window_width=457 -o initial_window_height=496 -e Updates --print-updates
                ;;
            "--ranger")
                kitty --hold --class=FloaTerm -o initial_window_width=844 -o initial_window_height=328 -e ranger
                ;;
            "--nvim")
                kitty -e nvim
                ;;
            "--music")
                kitty --class=FloaTerm -o initial_window_width=637 -o initial_window_height=412 -e ncmpcpp
                ;;
            "--fetch")
                kitty --class=FloaTerm -o initial_window_width=394 -o initial_window_height=580 -e ~/.local/bin/sysfetch
                ;;
        esac
        ;;
esac
