#!/bin/sh
# =============================================================
# gh0stzk
# https://github.com/gh0stzk/dotfiles
# This script controls the volume of your system, using pamixer.
# 24.04.2025
#
# Copyright (C) 2021-2025 gh0stzk <z0mbi3.zk@protonmail.com>
# Licensed under GPL-3.0 license
# =============================================================

# Icon directory
vol_dir="$HOME/.config/bspwm/src/assets"

notify() {
    dunstify -u low -h string:x-dunst-stack-tag:cvolum "$@"
}

# Get volume status
get_volume() {
    status=$(pamixer --get-volume-human)

    if [ "$status" = "muted" ]; then
        echo "muted"
    else
        echo "$status" | sed 's/%//'
    fi
}

# Determine icon based on status
get_icon() {
    current_vol=$(get_volume)

    if [ "$current_vol" = "muted" ] || [ "$current_vol" -eq 0 ]; then
        icon="$vol_dir/mute.png"
    else
        icon="$vol_dir/vol.png"
    fi
}

# Show notification
show_notification() {
    get_icon
    message="Volumen: $(get_volume)"
    echo "$message" | grep -q "muted" || message="${message}%"
    notify -i "$icon" "$message"
}

# Adjust volume
adjust_volume() {
    pamixer --unmute
    pamixer --allow-boost --set-limit 150 "$@"
    show_notification
}

# Toggle mute
toggle_mute() {
    pamixer --toggle-mute
    get_icon
    if [ "$(pamixer --get-mute)" = "true" ]; then
        message="Muted"
    else
        message="Unmuted"
    fi
    notify -i "$icon" "$message"
}

# Handle options
case $1 in
    --get)  get_volume ;;
    --inc)  adjust_volume -i 5 ;;
    --dec)  adjust_volume -d 5 ;;
    --toggle) toggle_mute ;;
    *)      echo "$(get_volume)%" ;;
esac
