##################
# video settings #
##################

vo=x11
hwdec=no

cache=yes
demuxer-max-bytes=300MiB
demuxer-max-back-bytes=150MiB

# Disable the On Screen Controller (OSC).
osc=no
title-bar=no
