#!/bin/sh
# =============================================================
# gh0stzk
# https://github.com/gh0stzk/dotfiles
# Get volume info for eww bar.
# 23.09.2023 12:30:34
#
# Copyright (C) 2021-2025 gh0stzk <z0mbi3.zk@protonmail.com>
# Licensed under GPL-3.0 license
# =============================================================

get_vol () {
    volumen=$(pamixer --get-volume-human | tr -d '%')
    [ "$volumen" = "muted" ] && echo "0" || echo "${volumen}"
}

get_icon () {
    vol=$(get_vol)
    echo "images/$( [ "$vol" = "0" ] && echo "mute" || echo "volume" ).png"
}

case "$1" in
    --vol) get_vol ;;
    --icon) get_icon ;;
    --toggle-muted) pamixer -t ;;
esac
