---
backup_dir: /home/{{ username }}/config_backups

packages:
  - neovim
  - alacritty
  - base-devel
  - rustup
  - pacman-contrib
  - bspwm
  - polybar
  - sxhkd
  - alacritty
  - brightnessctl
  - dunst
  - rofi
  - lsd
  - jq
  - polkit-gnome
  - git
  - playerctl
  - mpd
  - ncmpcpp
  - geany
  - ranger
  - mpc
  - picom
  - feh
  - ueberzug
  - maim
  - pamixer
  - libwebp
  - webp-pixbuf-loader
  - xorg-xprop
  - xorg-xkill
  - xdg-user-dirs
  - physlock
  - papirus-icon-theme
  - ttf-jetbrains-mono
  - ttf-jetbrains-mono-nerd
  - ttf-terminus-nerd
  - ttf-inconsolata
  - ttf-joypixels
  - zsh
  - zsh-autosuggestions
  - zsh-history-substring-search
  - zsh-syntax-highlighting

config_folders:
  - bspwm
  - alacritty
  - picom
  - rofi
  - eww
  - sxhkd
  - dunst
  - polybar
  - ncmpcpp
  - nvim
  - ranger
  - zsh
  - mpd
  - paru

rice_folders:
  - /home/{{ username }}/.config
  - /home/{{ username }}/.local/bin
  - /home/{{ username }}/.local/share/applications
  - /home/{{ username }}/.local/share/fonts
  - /home/{{ username }}/.local/share/asciiart

cleanup_folders:
  - /home/{{ username }}/paru-bin
  - /home/{{ username }}/.cargo
  - /home/{{ username }}/.rustup
  - /home/.cache/paru/clone/eww
