#!/usr/bin/env bash

FILE="$HOME/.cache/eww_andrea-sidebar.lock"
CFG="$HOME/.config/bspwm/rices/andrea/arin/sidedar"
 
run_eww() {
	eww --config "$CFG" open-many \
			resources \
			logout \
			suspend \
			lock \
			reboot \
			shutdown \
			quotes
}

if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	eww --config "$CFG" close resources logout suspend lock reboot shutdown quotes
	rm "$FILE"
fi
