#!/usr/bin/env bash
#  ██████╗ ██████╗ ███████╗███╗   ██╗██████╗  █████╗     ██████╗ ██╗ ██████╗███████╗
#  ██╔══██╗██╔══██╗██╔════╝████╗  ██║██╔══██╗██╔══██╗    ██╔══██╗██║██╔════╝██╔════╝
#  ██████╔╝██████╔╝█████╗  ██╔██╗ ██║██║  ██║███████║    ██████╔╝██║██║     █████╗
#  ██╔══██╗██╔══██╗██╔══╝  ██║╚██╗██║██║  ██║██╔══██║    ██╔══██╗██║██║     ██╔══╝
#  ██████╔╝██║  ██║███████╗██║ ╚████║██████╔╝██║  ██║    ██║  ██║██║╚██████╗███████╗
#  ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═════╝ ╚═╝  ╚═╝    ╚═╝  ╚═╝╚═╝ ╚═════╝╚══════╝
#  Author  :  z0mbi3
#  Url     :  https://github.com/gh0stzk/dotfiles
#  About   :  This file will configure and launch the rice.
#

# Set bspwm configuration for Brenda
set_bspwm_config() {
	bspc config border_width 0
	bspc config top_padding 50
	bspc config bottom_padding 2
	bspc config left_padding 2
	bspc config right_padding 2
	bspc config normal_border_color "#475258"
	bspc config active_border_color "#c0caf5"
	bspc config focused_border_color "#a7c080"
	bspc config presel_feedback_color "#e67e80"
}

# Set alacritty colorscheme
set_alacritty_config() {
	cat >"$HOME"/.config/alacritty/rice-colors.toml <<EOF
# (Everforest) color scheme for Brenda Rice

# Default colors
[colors.primary]
background = "#2d353b"
foreground = "#d3c6aa"

# Cursor colors
[colors.cursor]
cursor = "#d3c6aa"
text = "#2d353b"

# Normal colors
[colors.normal]
black   = "#475258"
red     = "#e67e80"
green   = "#a7c080"
yellow  = "#dbbc7f"
blue    = "#7fbbb3"
magenta = "#d699b6"
cyan    = "#83c092"
white   = "#d3c6aa"

# Bright colors
[colors.bright]
black   = "#475258"
red     = "#e67e80"
green   = "#a7c080"
yellow  = "#dbbc7f"
blue    = "#7fbbb3"
magenta = "#d699b6"
cyan    = "#83c092"
white   = "#d3c6aa"
EOF
}

# Set kitty colorscheme
set_kitty_config() {
  cat >"$HOME"/.config/kitty/current-theme.conf <<EOF
## This file is autogenerated, do not edit it, instead edit the Theme.sh file inside the rice directory.
## (Everforest) color scheme for Brenda Rice


# The basic colors
foreground              #d3c6aa
background              #2d353b
selection_foreground    #2d353b
selection_background    #83c092

# Cursor colors
cursor                  #d3c6aa
cursor_text_color       #2d353b

# URL underline color when hovering with mouse
url_color               #7fbbb3

# Kitty window border colors
active_border_color     #d699b6
inactive_border_color   #475258
bell_border_color       #dbbc7f

# Tab bar colors
active_tab_foreground   #2d353b
active_tab_background   #d699b6
inactive_tab_foreground #d3c6aa
inactive_tab_background #475258
tab_bar_background      #2d353b

# The 16 terminal colors

# black
color0 #475258
color8 #475258

# red
color1 #e67e80
color9 #e67e80

# green
color2  #a7c080
color10 #a7c080

# yellow
color3  #dbbc7f
color11 #dbbc7f

# blue
color4  #7fbbb3
color12 #7fbbb3

# magenta
color5  #d699b6
color13 #d699b6

# cyan
color6  #83c092
color14 #83c092

# white
color7  #d3c6aa
color15 #d3c6aa
EOF

killall -USR1 kitty
}

# Set compositor configuration
set_picom_config() {
	sed -i "$HOME"/.config/bspwm/picom.conf \
		-e "s/normal = .*/normal =  { fade = true; shadow = true; }/g" \
		-e "s/shadow-color = .*/shadow-color = \"#000000\"/g" \
		-e "s/corner-radius = .*/corner-radius = 6/g" \
		-e "s/\".*:class_g = 'Alacritty'\"/\"100:class_g = 'Alacritty'\"/g" \
		-e "s/\".*:class_g = 'kitty'\"/\"100:class_g = 'kitty'\"/g" \
		-e "s/\".*:class_g = 'FloaTerm'\"/\"100:class_g = 'FloaTerm'\"/g"
}

# Set dunst notification daemon config
set_dunst_config() {
	sed -i "$HOME"/.config/bspwm/dunstrc \
		-e "s/transparency = .*/transparency = 0/g" \
		-e "s/frame_color = .*/frame_color = \"#2d353b\"/g" \
		-e "s/separator_color = .*/separator_color = \"#d3c6aa\"/g" \
		-e "s/font = .*/font = JetBrainsMono NF Medium 9/g" \
		-e "s/foreground='.*'/foreground='#7fbbb3'/g"

	sed -i '/urgency_low/Q' "$HOME"/.config/bspwm/dunstrc
	cat >>"$HOME"/.config/bspwm/dunstrc <<-_EOF_
		[urgency_low]
		timeout = 3
		background = "#2d353b"
		foreground = "#d3c6aa"

		[urgency_normal]
		timeout = 6
		background = "#2d353b"
		foreground = "#d3c6aa"

		[urgency_critical]
		timeout = 0
		background = "#2d353b"
		foreground = "#d3c6aa"
	_EOF_
}

# Set eww colors
set_eww_colors() {
	cat >"$HOME"/.config/bspwm/eww/colors.scss <<EOF
// Eww colors for Brenda rice
\$bg: #2d353b;
\$bg-alt: #272e33;
\$fg: #d3c6aa;
\$black: #475258;
\$lightblack: #262831;
\$red: #e67e80;
\$blue: #7fbbb3;
\$cyan: #83c092;
\$magenta: #d699b6;
\$green: #a7c080;
\$yellow: #dbbc7f;
\$archicon: #0f94d2;
EOF
}

# Set jgmenu colors for Brenda
set_jgmenu_colors() {
	sed -i "$HOME"/.config/bspwm/jgmenurc \
		-e 's/color_menu_bg = .*/color_menu_bg = #2d353b/' \
		-e 's/color_norm_fg = .*/color_norm_fg = #d3c6aa/' \
		-e 's/color_sel_bg = .*/color_sel_bg = #475258/' \
		-e 's/color_sel_fg = .*/color_sel_fg = #d3c6aa/' \
		-e 's/color_sep_fg = .*/color_sep_fg = #a7c080/'
}

# Set rofi colors
set_launcher_config() {
	cat >"$HOME"/.config/bspwm/src/rofi-themes/shared.rasi <<EOF
// Rofi colors for Brenda

* {
    font: "JetBrainsMono NF Bold 9";
    background: #2d353b;
    background-alt: #2d353bE0;
    foreground: #d3c6aa;
    selected: #7fbbb3;
    active: #a7c080;
    urgent: #e67e80;
    
    img-background: url("~/.config/bspwm/rices/brenda/rofi.webp", width);
}
EOF
}

# Launch the bar
launch_bars() {

	for mon in $(polybar --list-monitors | cut -d":" -f1); do
		MONITOR=$mon polybar -q brenda -c "${rice_dir}"/config.ini &
	done

}

### ---------- Apply Configurations ---------- ###

set_bspwm_config
set_alacritty_config
set_kitty_config
set_picom_config
set_eww_colors
set_jgmenu_colors
set_dunst_config
set_launcher_config
launch_bars
