#!/bin/sh
#
#  ┳━┓┳━┓0┏┓┓┳━┓┏━┓┓ ┳
#  ┃┳┛┃━┫┃┃┃┃┃━┃┃ ┃┃┃┃
#  ┃┗┛┛ ┃┃┃┗┛┻━┛┛━┛┗┻┛
#     ┳━┓┳ ┓┳┏ ┳━┓
#     ┃━┛┃ ┃┣┻┓┣━ 
#     ┇  ┗━┛┃ ┛┻━┛
#    ┓━┓┳┏ ┳ ┓┳  ┳
#    ┗━┓┣┻┓┃ ┃┃  ┃
#    ━━┛┇ ┛┗━┛┗━┛┗━┛
#
# the worst color script
# by xero <http://0w.nz>

cat << 'EOF'
[1;97m                  .................
[1;97m             .syhhso++++++++/++osyyhys+.
[1;97m          -oddyo+o+++++++++++++++o+oo+osdms:
[1;97m        :dmyo++oosssssssssssssssooooooo+/+ymm+`
[1;97m       hmyo++ossyyhhddddddddddddhyyyssss+//+ymd-
[1;97m     -mho+oosyhhhddmmmmmmmmmmmmmmddhhyyyso+//+hN+
[1;97m     my+++syhhhhdmmNNNNNNNNNNNNmmmmmdhhyyyyo//+sd:
[1;97m    hs//+oyhhhhdmNNNNNNNNNNNNNNNNNNmmdhyhhhyo//++y
[1;97m    s+++shddhhdmmNNNNNNNNNNNNNNNNNNNNmdhhhdhyo/++/
[1;97m    'hs+shmmmddmNNNNNNNNNNNNNNNNNNNNNmddddddhs+oh/
[1;97m     shsshdmmmmmNNMMMMMMMMMMMNNNNNNNNmmmmmmdhssdh-
[1;97m      +ssohdmmmmNNNNNMMMMMMMMNNNNNNmmmmmNNmdhhhs:`
[1;97m  -+oo++////++sydmNNNNNNNNNNNNNNNNNNNdyyys/--://+//:
[1;97m  d/+hmNNNmmdddhhhdmNNNNNNNNNNNNNNNmdhyyyhhhddmmNmdyd-
[1;97m  ++--+ymNMMNNNNNNmmmmNNNNNNNNNNNmdhddmNNMMMMMMNmhyss
[1;97m   /d+` -+ydmNMMMMMMNNmNMMMMMMMmmmmNNMMMMMNNmh- :sdo
[1;97m    sNo   ` /ohdmNNMMMMNNMMMMMNNNMMMMMNmdyo/ `  hNh
[1;97m     M+'     ``-/oyhmNNMNhNMNhNMMMMNmho/ `     'MN/
[1;97m     d+'         `-+osydh0w.nzmNNmho:          'mN:
[1;97m    +o/             ` :oo+:s :+o/-`            -dds
[1;97m   :hdo       [0;31mx[1;97m    `-/ooss:':+ooo: `    [0;31m0[1;97m      :sdm+
[1;97m  +dNNNh+         :ydmNNm'   `sddmyo          +hmNmds
[1;97m dhNMMNNNNmddhsyhdmmNNNM:      NNmNmhyo+oyyyhmNMMNmysd
[1;97m ydNNNNNh+/++ohmMMMMNMNh       oNNNNNNNmho++++yddhyssy
[1;97m              `:sNMMMMN'       `mNMNNNd/`
    [1;91mXXXX[0;31mXXXX[1;93mX[1;97m y/hMMNm/  .dXb.  -hdmdy: ` [0;34mXXX[1;97mXXXX[0;37mXXXX
    [1;91mXXXX[0;31mXXXX[1;97m `o+hNNds. -ymNNy-  .yhys+/`` [0;34mXX[1;97mXXXX[0;37mXXXX
    [1;91mXXXX[0;31mXXXX[1;97m +-+//o/+odMNMMMNdmh++////-/s [0;34mXX[1;97mXXXX[0;37mXXXX
    [1;91mXXXX[0;31mXXX[1;97m mhNd -+d/+myo++ysy/hs -mNsdh/ [0;34mXX[1;97mXXXX[0;37mXXXX
    [1;91mXXXX[0;31mXXXX[1;97m mhMN+ dMm-/-smy-::dMN/sMMmdo [0;34mXX[1;97mXXXX[0;37mXXXX
    [1;91mXXXX[0;31mXXXX[1;93mXX[1;97m NMy+NMMh oMMMs yMMMyNMMs+ [0;34mXXX[1;97mXXXX[0;37mXXXX
    [1;91mXXXX[0;31mXXXX[1;93mXXX[1;97m dy-hMMm+dMMMdoNMMh ydo [1;94mX[0;34mXXXX[1;97mXXXX[0;37mXXXX
    [1;91mXXXX[0;31mXXXX[1;93mXXXX[0;33mX [1;97m smm 'NMMy dms  sm  [1;94mXX[0;34mXXXX[1;97mXXXX[0;37mXXXX
    [1;91mXXXX[0;31mXXXX[1;93mXXXX[0;33mXX                   [1;94mXXX[0;34mXXXX[1;97mXXXX[0;37mXXXX
    [1;91mXXXX[0;31mXXXX[1;93mXXXX[0;33mXXXX[1;95mXXXX[0;35mXXXX[1;92mXXXX[0;32mXXXX[1;94mXXXX[0;34mXXXX[1;97mXXXX[0;37mXXXX
    [1;91mXXXX[0;31mXXXX[1;93mXXXX[0;33mXXXX[1;95mXXXX[0;35mXXXX[1;92mXXXX[0;32mXXXX[1;94mXXXX[0;34mXXXX[1;97mXXXX[0;37mXXXX
    [1;91mXXXX[0;31mXXXX[1;93mXXXX[0;33mXXXX[1;95mXXXX[0;35mXXXX[1;92mXXXX[0;32mXXXX[1;94mXXXX[0;34mXXXX[1;97mXXXX[0;37mXXXX
    [1;91mXXXX[0;31mXXXX[1;93mXXXX[0;33mXXXX[1;95mXXXX[0;35mXXXX[1;92mXXXX[0;32mXXXX[1;94mXXXX[0;34mXXXX[1;97mXXXX[0;37mXXXX
    [1;91mXXXX[0;31mXXXX[1;93mXXXX[0;33mXXXX[1;95mXXXX[0;35mXXXX[1;92mXXXX[0;32mXXXX[1;94mXXXX[0;34mXXXX[1;97mXXXX[0;37mXXXX
    [1;91mXXXX[0;31mXXXX[1;93mXXXX[0;33mXXXX[1;95mXXXX[0;35mXXXX[1;92mXXXX[0;32mXXXX[1;94mXXXX[0;34mXXXX[1;97mXXXX[0;37mXXXX

EOF
 
