#!/bin/bash

# ANSI color scheme script by pfh
# Source: http://crunchbang.org/forums/viewtopic.php?pid=143700#p143700
# Initializing mod by lolilolicon from Archlinux

f=3 b=4
for j in f b; do
  for i in {0..7}; do
    printf -v $j$i %b "\e[${!j}${i}m"
  done
done
for i in {0..7}; do
    printf -v fbright$i %b "\e[9${i}m"
done
bld=$'\e[1m'
rst=$'\e[0m'
inv=$'\e[7m'

cat << EOF

 $f3 ▄      $f1      ▄▄      $f2      ▄▄      $f4      ▄▄      $f5      ▄▄      $f6      ▄▄     
 $f3 ███▄▄  $f1   ██▬██▬██   $f2   ██▬██▬██   $f4   ██▬██▬██   $f5   ██▬██▬██   $f6   ██▬██▬██  
 $f3 █████▀▀$f1     ████     $f2     ████     $f4     ████     $f5     ████     $f6     ████    
 $f3 █▀▀    $f1   ▄██  ██▄   $f2   ▄██  ██▄   $f4   ▄██  ██▄   $f5   ▄██  ██▄   $f6   ▄██  ██▄  
 $f3 █      $f1 ▄▄▄▀█  █▀▄▄▄ $f2 ▄▄▄▀█  █▀▄▄▄ $f4 ▄▄▄▀█  █▀▄▄▄ $f5 ▄▄▄▀█  █▀▄▄▄ $f6 ▄▄▄▀█  █▀▄▄▄
 $f3▄█▄     $f1 ███▀████▀███ $f2 ███▀████▀███ $f4 ███▀████▀███ $f5 ███▀████▀███ $f6 ███▀████▀███
            $f1  ▀  ▀        $f2  ▀  ▀        $f4  ▀  ▀        $f5  ▀  ▀        $f6  ▀  ▀       
$bld
 $fbright3 ▄      $fbright1      ▄▄      $fbright2      ▄▄      $fbright4      ▄▄      $fbright5      ▄▄      $fbright6      ▄▄     
 $fbright3 ███▄▄  $fbright1   ██▬██▬██   $fbright2   ██▬██▬██   $fbright4   ██▬██▬██   $fbright5   ██▬██▬██   $fbright6   ██▬██▬██  
 $fbright3 █████▀▀$fbright1     ████     $fbright2     ████     $fbright4     ████     $fbright5     ████     $fbright6     ████    
 $fbright3 █▀▀    $fbright1   ▄██  ██▄   $fbright2   ▄██  ██▄   $fbright4   ▄██  ██▄   $fbright5   ▄██  ██▄   $fbright6   ▄██  ██▄  
 $fbright3 █      $fbright1 ▄▄▄▀█  █▀▄▄▄ $fbright2 ▄▄▄▀█  █▀▄▄▄ $fbright4 ▄▄▄▀█  █▀▄▄▄ $fbright5 ▄▄▄▀█  █▀▄▄▄ $fbright6 ▄▄▄▀█  █▀▄▄▄
 $fbright3▄█▄     $fbright1 ███▀████▀███ $fbright2 ███▀████▀███ $fbright4 ███▀████▀███ $fbright5 ███▀████▀███ $fbright6 ███▀████▀███
            $fbright1  ▀  ▀        $fbright2  ▀  ▀        $fbright4  ▀  ▀        $fbright5  ▀  ▀        $fbright6  ▀  ▀       
$rst  
EOF
