#!/usr/bin/env bash

STATUS="$(mpc status)"

get_status() {
	if [[ $STATUS == *"[playing]"* ]]; then
		echo "images/icons/music/pause-button.png"
	else
		echo "images/icons/music/play-button.png"
	fi
}

if [[ "$1" == "--status" ]]; then
	get_status
fi
