#!/usr/bin/env bash

CFG="$HOME/.config/bspwm/rices/andrea/arin/sidedar"

close_eww() {
	eww --config "$CFG" close resources logout suspend lock reboot shutdown quotes
}

case "$1" in
	--lock)
		close_eww
		physlock -d
		;;
	--logout)
		close_eww
		bspc quit
		;;
	--suspend)
		close_eww
		systemctl suspend
		;;
	--reboot)
		close_eww
		systemctl reboot
		;;
	--shutdown)
		close_eww
		systemctl poweroff
		;;
	*)
		echo "error";;
esac
	
