#!/bin/bash

if [[ "$1" == "--tr" ]]; then
	termite & disown

elif [[ "$1" == "--ff" ]]; then
	firefox & disown

elif [[ "$1" == "--fm" ]]; then
	thunar ~ & disown

elif [[ "$1" == "--ge" ]]; then
	geany & disown

elif [[ "$1" == "--dc" ]]; then
	discord &

elif [[ "$1" == "--tg" ]]; then
	telegram-desktop &

elif [[ "$1" == "--rd" ]]; then
	firefox --new-tab "https://reddit.com"

elif [[ "$1" == "--ml" ]]; then
	firefox --new-tab "https://mail.google.com"

elif [[ "$1" == "--pow" ]]; then
	xfce4-power-manager-settings &

elif [[ "$1" == "--nm" ]]; then
	networkmanager_dmenu
	
elif [[ "$1" == "--zo" ]]; then
	termite --hold -t sysfetch -e $HOME/.local/bin/sysfetch
	
elif [[ "$1" == "--up" ]]; then
	termite --hold -t updating -e "yay -Syyuu --devel"

fi
