#!/usr/bin/env bash

if [[ "$1" == "--tr" ]]; then
	Term --ot

elif [[ "$1" == "--ff" ]]; then
	firefox & disown
	
elif [[ "$1" == "--menu" ]]; then
	rofi -no-lazy-grab -show drun -theme $HOME/.config/bspwm/rices/$RICETHEME/launcher.rasi & disown

elif [[ "$1" == "--fm" ]]; then
	thunar ~ & disown

elif [[ "$1" == "--ge" ]]; then
	geany & disown

elif [[ "$1" == "--tg" ]]; then
	telegram-desktop &

elif [[ "$1" == "--rd" ]]; then
	firefox --new-tab "https://reddit.com"

elif [[ "$1" == "--ml" ]]; then
	firefox --new-tab "https://mail.google.com"

elif [[ "$1" == "--nm" ]]; then
	networkmanager_dmenu
	
elif [[ "$1" == "--zo" ]]; then
	Term --of
	
elif [[ "$1" == "--up" ]]; then
	Term --ou

fi
