#!/usr/bin/env bash

if [[ "$1" == "--tr" ]]; then
	Term --ot

elif [[ "$1" == "--ff" ]]; then
	firefox & disown

elif [[ "$1" == "--fm" ]]; then
	thunar ~ & disown

elif [[ "$1" == "--ge" ]]; then
	geany & disown

elif [[ "$1" == "--tg" ]]; then
	telegram-desktop &
	
elif [[ "$1" == "--wa" ]]; then
	whatsapp-nativefier --disable-gpu
	
elif [[ "$1" == "--up" ]]; then
	Term --ou

fi
