#!/usr/bin/env bash
#  ██╗   ██╗ █████╗ ███████╗██╗
#  ╚██╗ ██╔╝██╔══██╗██╔════╝██║
#   ╚████╔╝ ███████║█████╗  ██║
#    ╚██╔╝  ██╔══██║██╔══╝  ██║
#     ██║   ██║  ██║███████╗███████╗
#     ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝
#  Author  :  z0mbi3
#  Url     :  https://github.com/gh0stzk/dotfiles
#  About   :  This file will configure and launch the rice.
#

# Set bspwm configuration for Yael
set_bspwm_config() {
	bspc config border_width 0
	bspc config top_padding 38
	bspc config bottom_padding 2
	bspc config left_padding 2
	bspc config right_padding 2
	bspc config normal_border_color "#33b1ff"
	bspc config active_border_color "#42be65"
	bspc config focused_border_color "#33b1ff"
	bspc config presel_feedback_color "#ee5396"
}

# Reload terminal colors
set_term_config() {
	cat >"$HOME"/.config/alacritty/rice-colors.toml <<EOF
# (OxoCarbon) color scheme for Yael Rice

# Default colors
[colors.primary]
background = "#161616"
foreground = "#ffffff"

# Cursor colors
[colors.cursor]
cursor = "#ffffff"
text = "#161616"

# Normal colors
[colors.normal]
black = "#262626"
red = "#ee5396"
green = "#42be65"
yellow = "#ffe97b"
blue =  "#33b1ff"
magenta = "#ff7eb6"
cyan = "#3ddbd9"
white = "#dde1e6"

# Bright colors
[colors.bright]
black = "#393939"
red = "#ee5396"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
magenta = "#ff7eb6"
cyan = "#3ddbd9"
white = "#ffffff"
EOF
}

# Set kitty colorscheme
set_kitty_config() {
  cat >"$HOME"/.config/kitty/current-theme.conf <<EOF
## This file is autogenerated, do not edit it, instead edit the Theme.sh file inside the rice directory.
## (OxoCarbon) color scheme for Yael Rice


# The basic colors
foreground              #ffffff
background              #161616
selection_foreground    #161616
selection_background    #33b1ff

# Cursor colors
cursor                  #ffffff
cursor_text_color       #161616

# URL underline color when hovering with mouse
url_color               #42be65

# Kitty window border colors
active_border_color     #33b1ff
inactive_border_color   #262626
bell_border_color       #ffe97b

# Tab bar colors
active_tab_foreground   #161616
active_tab_background   #33b1ff
inactive_tab_foreground #161616
inactive_tab_background #3ddbd9
tab_bar_background      #161616

# The 16 terminal colors

# black
color0 #262626
color8 #393939

# red
color1 #ee5396
color9 #ee5396

# green
color2  #42be65
color10 #42be65

# yellow
color3  #ffe97b
color11 #ffe97b

# blue
color4  #33b1ff
color12 #33b1ff

# magenta
color5  #ff7eb6
color13 #ff7eb6

# cyan
color6  #3ddbd9
color14 #3ddbd9

# white
color7  #dde1e6
color15 #ffffff
EOF

killall -USR1 kitty
}

# Set compositor configuration
set_picom_config() {
	sed -i "$HOME"/.config/bspwm/picom.conf \
		-e "s/normal = .*/normal =  { fade = true; shadow = true; }/g" \
		-e "s/shadow-color = .*/shadow-color = \"#000000\"/g" \
		-e "s/corner-radius = .*/corner-radius = 6/g" \
		-e "s/\".*:class_g = 'Alacritty'\"/\"100:class_g = 'Alacritty'\"/g" \
    -e "s/\".*:class_g = 'kitty'\"/\"100:class_g = 'kitty'\"/g" \
		-e "s/\".*:class_g = 'FloaTerm'\"/\"100:class_g = 'FloaTerm'\"/g"
}

# Set dunst notification daemon config
set_dunst_config() {
	sed -i "$HOME"/.config/bspwm/dunstrc \
		-e "s/transparency = .*/transparency = 0/g" \
		-e "s/frame_color = .*/frame_color = \"#161616\"/g" \
		-e "s/separator_color = .*/separator_color = \"#3ddbd9\"/g" \
		-e "s/font = .*/font = JetBrainsMono NF Medium 9/g" \
		-e "s/foreground='.*'/foreground='#33b1ff'/g"

	sed -i '/urgency_low/Q' "$HOME"/.config/bspwm/dunstrc
	cat >>"$HOME"/.config/bspwm/dunstrc <<-_EOF_
		[urgency_low]
		timeout = 3
		background = "#161616"
		foreground = "#ffffff"

		[urgency_normal]
		timeout = 6
		background = "#161616"
		foreground = "#ffffff"

		[urgency_critical]
		timeout = 0
		background = "#161616"
		foreground = "#ffffff"
	_EOF_
}

# Set eww colors
set_eww_colors() {
	cat >"$HOME"/.config/bspwm/eww/colors.scss <<EOF
// Eww colors for Yael rice
\$bg: #161616;
\$bg-alt: #212121;
\$fg: #ffffff;
\$black: #393939;
\$lightblack: #262831;
\$red: #ee5396;
\$blue: #33b1ff;
\$cyan: #3ddbd9;
\$magenta: #ff7eb6;
\$green: #42be65;
\$yellow: #ffe97b;
\$archicon: #0f94d2;
EOF
}

# Set jgmenu colors for Yael
set_jgmenu_colors() {
	sed -i "$HOME"/.config/bspwm/jgmenurc \
		-e 's/color_menu_bg = .*/color_menu_bg = #161616/' \
		-e 's/color_norm_fg = .*/color_norm_fg = #ffffff/' \
		-e 's/color_sel_bg = .*/color_sel_bg = #212121/' \
		-e 's/color_sel_fg = .*/color_sel_fg = #ffffff/' \
		-e 's/color_sep_fg = .*/color_sep_fg = #33b1ff/'
}

# Set rofi colors
set_launcher_config() {
	cat >"$HOME"/.config/bspwm/src/rofi-themes/shared.rasi <<EOF
// Rofi colors for Yael

* {
    font: "JetBrainsMono NF Bold 9";
    background: #161616;
    background-alt: #161616E0;
    foreground: #ffffff;
    selected: #33b1ff;
    active: #42be65;
    urgent: #ee5396;
    
    img-background: url("~/.config/bspwm/rices/yael/rofi.webp", width);
}
EOF
}

# Launch the bar
launch_bars() {

	for mon in $(polybar --list-monitors | cut -d":" -f1); do
		MONITOR=$mon polybar -q yael-cohen -c "${rice_dir}"/config.ini &
	done

}

### ---------- Apply Configurations ---------- ###

set_bspwm_config
set_term_config
set_kitty_config
set_picom_config
launch_bars
set_eww_colors
set_jgmenu_colors
set_dunst_config
set_launcher_config
