font_family JetBrainsMono NF
font_size 11

cursor_shape block
cursor_stop_blinking_after 0
scrollback_lines 2000
copy_on_select yes
mouse_hide_wait 0
select_by_word_characters @-./_~?&=%+#a
enable_audio_bell no
bell_on_tab "🔔 "
remember_window_size  no
window_border_width 1pt
draw_minimal_borders yes
window_padding_width 10
inactive_text_alpha 0.6
hide_window_decorations yes
confirm_os_window_close 0

## TABS
tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted
tab_bar_align           left
tab_bar_min_tabs        2
tab_bar_margin_width    0.0
tab_bar_margin_height   0.5 1.5
inactive_tab_font_style         normal
tab_activity_symbol             " ● "

tab_title_template              "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
active_tab_title_template       "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"

include current-theme.conf
