#! /bin/sh

#    ____ ____  ______        ____  __ 
#   | __ ) ___||  _ \ \      / /  \/  |
#   |  _ \___ \| |_) \ \ /\ / /| |\/| |
#   | |_) |__) |  __/ \ V  V / | |  | |
#   |____/____/|_|     \_/\_/  |_|  |_|
#                                    z0mbi3 config..


unset RICETHEME
RICETHEME=$(<$HOME/.config/bspwm/rice.cfg)
export RICETHEME=$RICETHEME
unset wallimage
wallimage=$(shuf -en1 ~/.config/bspwm/$RICETHEME/*.webp)
PATH="$HOME/.config/bspwm/scripts:$PATH"


function launch() {
  local running
  running="$(pidof "$1")"
  [ "$running" ] && kill -9 $(pidof $1)
  eval "$* &"
}

function killeww() {
	
	if [[ `pidof eww` ]]; then 
		pkill eww
	fi
}

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V' 'VI'
		let name++
	done
}
workspaces

################################ Launch some nice apps

	if [ $RICETHEME == emilia ]; then
	
				killeww
				launch polybar -q z0mbi3b4r -c ~/.config/bspwm/$RICETHEME/polybar/config.ini &
				launch dunst -config ~/.config/bspwm/dunstrc-dark &
			
	elif [ $RICETHEME == jan ]; then
			
				killeww
				launch polybar -q main -c ~/.config/bspwm/$RICETHEME/polybar/config.ini &
				launch dunst -config ~/.config/bspwm/dunstrc-dark &
				
	elif [ $RICETHEME == aline ]; then
		
				killeww
				launch polybar -q aline-bar -c ~/.config/bspwm/$RICETHEME/polybar/config.ini &
				launch dunst -config ~/.config/bspwm/dunstrc-light &
				
	elif [ $RICETHEME == isabel ]; then
		
				killeww
				launch polybar -q isa-bar -c ~/.config/bspwm/$RICETHEME/polybar/config.ini &
				launch dunst -config ~/.config/bspwm/dunstrc-dark &
				
	elif [ $RICETHEME == cynthia ]; then
		
				killeww
				launch polybar -q cyn-bar -c ~/.config/bspwm/$RICETHEME/polybar/config.ini &
				launch dunst -config ~/.config/bspwm/dunstrc-dark &
				
	elif [ $RICETHEME == silvia ]; then
		
				killeww
				launch polybar -q cata-bar -c ~/.config/bspwm/$RICETHEME/polybar/config.ini &
				launch dunst -config ~/.config/bspwm/dunstrc-dark &
				
	elif [ $RICETHEME == melissa ]; then
		
				killeww
				killall polybar
				polybar -q mel-bar -c ~/.config/bspwm/$RICETHEME/polybar/config.ini &
				polybar -q mel2-bar -c ~/.config/bspwm/$RICETHEME/polybar/config.ini &
				launch dunst -config ~/.config/bspwm/dunstrc-dark &
				
	fi

				
	if [ $RICETHEME == andrea ]; then
		
		pkill polybar 
		pkill picom
		launch dunst -config ~/.config/bspwm/dunstrc-light &
		~/.config/bspwm/$RICETHEME/arin/launch_bar 
	fi
	

########### Global conf

bspc wm --adopt-orphans
launch sxhkd -c ~/.config/bspwm/sxhkdrc &
launch picom --config ~/.config/bspwm/$RICETHEME/picom.conf &
launch /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
launch feh --no-fehbg --bg-fill $wallimage
bspc config external_rules_command ~/.config/bspwm/scripts/external_rules
#nitrogen --restore &
xsetroot -cursor_name left_ptr

###########################################################################

#bspc monitor VGA1 -d I II III IV V VI

	if pacman -Qi bspwm-rounded-corners-git >/dev/null 2>&1; then
		bspc config border_radius                 10
	fi

#### bspwm conf #### 
bspc config window_gap                    5 
bspc config left_padding                  5
bspc config right_padding                 5

### Layout ###
bspc config single_monocle                true
bspc config split_ratio                   0.51
bspc config borderless_monocle            false
bspc config gapless_monocle               false
bspc config focus_follows_pointer         true 

### Mouse pointer actions ###
bspc config pointer_modifier              mod4 
bspc config pointer_action1               move 
bspc config pointer_action2               resize_side 
bspc config pointer_action3               resize_corner

bspc config automatic_scheme              longest_side
bspc config initial_polarity              second_child

bspc config remove_disabled_monitors      true 
bspc config merge_overlapping_monitors    true

bspc config pointer_motion_interval       5

#### BSPWM colors ####

	if [ $RICETHEME == emilia ]; then
	
#### Emilia Rice ####

bspc config border_width                  0
bspc config top_padding                   55
bspc config bottom_padding                5

bspc config normal_border_color		  "#202132" 
bspc config active_border_color	      "#202132"
bspc config focused_border_color	  "#000000"
bspc config presel_feedback_color	  "#070219"

	elif [ $RICETHEME == jan ]; then

#### Jan Rice ####

bspc config border_width                  1
bspc config top_padding                   55
bspc config bottom_padding                5

bspc config normal_border_color		  "#4C3A6D" 
bspc config active_border_color	      "#4C3A6D"
bspc config focused_border_color	  "#785DA5"
bspc config presel_feedback_color	  "#070219" 

	elif [ $RICETHEME == aline ]; then

#### Aline Rice ####

bspc config border_width                  1
bspc config top_padding                   45
bspc config bottom_padding                5

bspc config normal_border_color		  "#000000" 
bspc config active_border_color	      "#000000"
bspc config focused_border_color	  "#000000"
bspc config presel_feedback_color	  "#070219"

	elif [ $RICETHEME == isabel ]; then

#### Isabel Rice ####

bspc config border_width                  1
bspc config top_padding                   5
bspc config bottom_padding                45

bspc config normal_border_color		  "#333a48" 
bspc config active_border_color	      "#333a48"
bspc config focused_border_color	  "#333a48"
bspc config presel_feedback_color	  "#4f4f5b"

	elif [ $RICETHEME == andrea ]; then

#### Andrea Rice ####

bspc config border_width                  2
bspc config top_padding                   60
bspc config bottom_padding                5

bspc config normal_border_color		  "#161616" 
bspc config active_border_color	      "#161616"
bspc config focused_border_color	  "#161616"
bspc config presel_feedback_color	  "#4f4f5b"

	elif [ $RICETHEME == cynthia ]; then

#### Cynthia Rice ####

bspc config border_width                  0
bspc config top_padding                   40
bspc config bottom_padding                5

bspc config normal_border_color		  "#4C3A6D" 
bspc config active_border_color	      "#4C3A6D"
bspc config focused_border_color	  "#785DA5"
bspc config presel_feedback_color	  "#070219"

	elif [ $RICETHEME == silvia ]; then

#### Silvia Rice ####

bspc config border_width                  1
bspc config top_padding                   45
bspc config bottom_padding                5

bspc config normal_border_color		  "#bdae93" 
bspc config active_border_color	      "#bdae93"
bspc config focused_border_color	  "#bdae93"
bspc config presel_feedback_color	  "#4f4f5b"

	elif [ $RICETHEME == melissa ]; then

#### Melissa Rice ####

bspc config border_width                  2
bspc config top_padding                   30
bspc config bottom_padding                30

bspc config normal_border_color		  "#4c566a" 
bspc config active_border_color	      "#4c566a"
bspc config focused_border_color	  "#4c566a"
bspc config presel_feedback_color	  "#4f4f5b"

	fi

