#!/usr/bin/env bash

ID="$(ip link | awk '/state UP/ {print $2}')"
SSID="$(nmcli -t -f active,ssid dev wifi show | sed -n '1{s/SSID: //p}')"

net_stat () {
    if (ping -c 1 archlinux.org || ping -c 1 google.com) &>/dev/null; then
        if [[ $ID == e* ]]; then
            echo "Online"
            echo "images/wifi.png"
        else
            echo "$SSID"
            echo "images/wifi.png"
        fi
    else
        echo "Offline"
        echo "images/no-wifi.png"
    fi
}

case "$1" in
    --stat)
        net_stat | head -n1 ;;
    --icon)
        net_stat | tail -n1 ;;
esac
