#!/usr/bin/env bash
#  ███╗   ██╗███████╗████████╗██╗    ██╗ ██████╗ ██████╗ ██╗  ██╗
#  ████╗  ██║██╔════╝╚══██╔══╝██║    ██║██╔═══██╗██╔══██╗██║ ██╔╝
#  ██╔██╗ ██║█████╗     ██║   ██║ █╗ ██║██║   ██║██████╔╝█████╔╝
#  ██║╚██╗██║██╔══╝     ██║   ██║███╗██║██║   ██║██╔══██╗██╔═██╗
#  ██║ ╚████║███████╗   ██║   ╚███╔███╔╝╚██████╔╝██║  ██║██║  ██╗
#  ╚═╝  ╚═══╝╚══════╝   ╚═╝    ╚══╝╚══╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
#	gh0stzk
#	https://github.com/gh0stzk/dotfiles
#	Checks if you are connected to the internet and set values for eww bar.
#	23.09.2023 13:39:59

is_online() {
	ping -c 1 -W 1 archlinux.org &>/dev/null
}

ID=$(ip link | awk '/state UP/ {print $2}' | tr -d :)

ICON="images/no-wifi.png"
STATUS="Offline"

if is_online; then
	ICON="images/wifi.png"
	
    if [[ $ID == e* ]]; then
        STATUS="$ID"
    elif command -v nmcli &>/dev/null; then
        STATUS=$(nmcli -t -f active,ssid dev wifi show | sed -n '1{s/SSID: //p}')
    fi
fi

case "$1" in
    --stat) echo "$STATUS" ;;
    --icon) echo "$ICON" ;;
esac
