#!/usr/bin/env bash

# Checks if a list ($1) contains an element ($2)
contains() {
    [[ $1 =~ (^|[[:space:]])$2($|[[:space:]]) ]] && echo 1 || echo 0
}

print_workspaces() {
    local buf=""
    local desktops=$(bspc query -D --names | sort -u)
    local focused_desktop=$(bspc query -D -d focused --names)
    local occupied_desktops=$(bspc query -D -d .occupied --names)

    for d in $desktops; do
        if [[ "$focused_desktop" == "$d" ]]; then
            ws=$d
            icon="./images/pacman.png"
        elif [[ $(contains "$occupied_desktops" "$d") -eq 1 ]]; then
            ws=$d
            icon="./images/ghost.png"
        else
            ws=$d
            icon="./images/empty.png"
        fi

        buf+="(eventbox :cursor \"pointer\" (button :style \"background-image: url('$icon');\" :class \"icons\" :valign \"center\" :onclick \"bspc desktop -f $ws\"))"
    done
    
    echo "(box :class \"mainbars\" :spacing 10 :space-evenly \"false\" :vexpand \"true\" $buf)"
}

# Initial print
print_workspaces

# Listen to bspwm changes
bspc subscribe desktop node_transfer | while read -r _ ; do
    print_workspaces
done
