#!/usr/bin/env bash
#  ╦ ╦╦╔╦╗╔═╗  ╔╗ ╔═╗╦═╗
#  ╠═╣║ ║║║╣   ╠╩╗╠═╣╠╦╝
#  ╩ ╩╩═╩╝╚═╝  ╚═╝╩ ╩╩╚═
#	Simple script to hide/show polybar
#   Author: z0mbi3
#	url: https://github.com/gh0stzk

function hide() {
	
case "${RICETHEME}" in
    emilia|jan|aline|silvia|pamela)
        polybar-msg cmd hide | bspc config top_padding 5
        ;;
    isabel|cristina)
        polybar-msg cmd hide | bspc config bottom_padding 5
        ;;
    melissa|cynthia)
        polybar-msg cmd hide | bspc config top_padding 5 | bspc config bottom_padding 5
        ;;
    z0mbi3)
        eww -c "$HOME"/.config/bspwm/rices/z0mbi3/bar close bar | bspc config left_padding 5
        ;;
    andrea)
        eww -c "$HOME"/.config/bspwm/rices/andrea/arin close-all | bspc config top_padding 5
        ;;
    karla)
        eww -c "$HOME"/.config/bspwm/rices/karla/bar close bar & polybar-msg cmd hide | bspc config top_padding 5
        ;;
    *)
        echo "Error: Something fails dud.."
        ;;
esac
	
}

function unhide() {
	
case "${RICETHEME}" in
	emilia|jan|pamela)
		polybar-msg cmd show | bspc config top_padding 60
		;;
	aline)
		polybar-msg cmd show | bspc config top_padding 55
		;;
	silvia)
		polybar-msg cmd show | bspc config top_padding 50
		;;
	isabel)
		polybar-msg cmd show | bspc config bottom_padding 45
		;;
	melissa)
		polybar-msg cmd show | bspc config top_padding 42 | bspc config bottom_padding 40
		;;
	cynthia)
		polybar-msg cmd show | bspc config top_padding 50 | bspc config bottom_padding 50
		;;
	cristina)
		polybar-msg cmd show | bspc config bottom_padding 60
		;;
	z0mbi3)
		eww -c "$HOME"/.config/bspwm/rices/z0mbi3/bar open bar | bspc config left_padding 80
		;;
	karla)
		eww -c "$HOME"/.config/bspwm/rices/karla/bar open bar & polybar-msg cmd show | bspc config top_padding 65
		;;
	andrea)
		eww -c "$HOME"/.config/bspwm/rices/andrea/arin open-many \
		   search \
		   apps \
		   weather \
		   music \
		   system | bspc config top_padding 60
		;;
	*)
		echo "Error: Something fails dud.."
		;;
esac

}

case $1 in
	-h | --hide | hide)
		hide
		exit;;
	-u | --unhide | unhide)
		unhide
		exit;;
	*) # Invalid option
		echo "Error: Invalid option"
		exit;;
esac

