#! /bin/sh

# Author 	 -  z0mbi3
# Source 	 -  https://github.com/gh0stzk/dotfiles
# Maintainer -  z0mbi3.zk@protonmail.com

bspdir="$HOME/.config/bspwm"
polydir="$HOME/.config/bspwm/rices/$RICETHEME/polybar"

function launch() {
  local running
  running="$(pidof "$1")"
  [ "$running" ] && kill -9 $(pidof $1)
  eval "$* &"
}
function LaunchBar() {
	local launchpoly
	launchpoly="$(pidof "polybar")"
	[ "$launchpoly" ] && polybar-msg cmd quit
	eval "$* & disown"
}
function killeww() {
  if [[ `pidof eww` ]]; then 
		pkill eww
  fi
}
function ResetTermite() {
  if [[ `pidof termite` ]]; then 
		killall -USR1 termite
  fi
}
function ReloadTermite() {
  if [ -f "$HOME/.config/termite/config" ]; then
		cat $HOME/.config/bspwm/rices/$RICETHEME/termiterc > $HOME/.config/termite/config
		ResetTermite
  else
		mkdir -p $HOME/.config/termite/ && touch $HOME/.config/termite/config
		cat $HOME/.config/bspwm/rices/$RICETHEME/termiterc > $HOME/.config/termite/config
		ResetTermite
  fi
}

function SetBspwmConf() {
	bspc config border_width "$1"
	bspc config top_padding "$2"
	bspc config bottom_padding "$3"
	bspc config normal_border_color "$4" 
	bspc config active_border_color "$5"
	bspc config focused_border_color "$6"
	bspc config presel_feedback_color "$7"
}

function SetGirlFriendRice() {
	
	case $RICETHEME in
	
		emilia)
		
		  SetBspwmConf 0 60 5 "#202132" "#202132" "#202132" "#070219"	
		  		  
		  killeww
		  LaunchBar polybar -q emi-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark &
		  
		  ;;
			
		jan)
		
		  SetBspwmConf 0 60 5 "#4C3A6D" "#4C3A6D" "#785DA5" "#070219"	
		  
		  killeww
		  LaunchBar polybar -q main -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark &
		  
		  ;;
		    
		aline)
		
		  SetBspwmConf 0 50 5 "#000000" "#000000" "#000000" "#070219"	
		  
		  killeww
		  LaunchBar polybar -q aline-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-light &
		  
		  ;;
		  
		isabel)
		
		  SetBspwmConf 0 5 45 "#333a48" "#333a48" "#333a48" "#4f4f5b"	
		  
		  killeww
		  LaunchBar polybar -q isa-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark &
		  
		  ;;
		  
		cynthia)
		
		  SetBspwmConf 0 45 5 "#4C3A6D" "#4C3A6D" "#785DA5" "#070219"	
		  
		  killeww
		  LaunchBar polybar -q cyn-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark &
		  
		  ;;
		  
		silvia)
		
		  SetBspwmConf 0 45 5 "#bdae93" "#bdae93" "#bdae93" "#4f4f5b"	

		  killeww
		  LaunchBar polybar -q cata-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark &
		  
		  ;;
		
		melissa)
		
		  SetBspwmConf 0 42 40 "#4c566a" "#4c566a" "#4c566a" "#4f4f5b"		

		  killeww
		  LaunchBar polybar -q mel-bar -c ${polydir}/config.ini
		  polybar -q mel2-bar -c ${polydir}/config.ini & disown
		  launch dunst -config ${bspdir}/dunstrc-dark &
		  
		  ;;
		  
		pamela)
		
		  SetBspwmConf 0 60 5 "#bdae93" "#bdae93" "#bdae93" "#4f4f5b"	
		  
		  killeww
		  LaunchBar polybar -q pam1 -c ${polydir}/config.ini
		  polybar -q pam2 -c ${polydir}/config.ini & disown
		  polybar -q pam3 -c ${polydir}/config.ini & disown
		  polybar -q pam4 -c ${polydir}/config.ini & disown
		  polybar -q pam5 -c ${polydir}/config.ini & disown
		  polybar -q pam6 -c ${polydir}/config.ini & disown
		  launch dunst -config ${bspdir}/dunstrc-dark &
		  
		  ;;
		  
		cristina)
		
		  SetBspwmConf 0 10 60 "#bdae93" "#bdae93" "#bdae93" "#4f4f5b"
		  
		  killeww
		  LaunchBar polybar -q cristina-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark &
		  
		  ;;
		  
		andrea)
		
		  SetBspwmConf 0 60 5 "#161616" "#161616" "#161616" "#4f4f5b"
		  
		  pkill picom
		  polybar-msg cmd quit 
		  launch dunst -config ${bspdir}/dunstrc-light &
		  ~/.config/bspwm/rices/$RICETHEME/arin/launch_bar
		  
		  ;;
		  
	esac		
}

ReloadTermite

function AutoStartApps() {
	
	launch sxhkd -c ${bspdir}/sxhkdrc &
	launch picom --config ${bspdir}/rices/$RICETHEME/picom.conf &
	launch /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
	launch feh --no-fehbg --bg-fill $wallimage
	#nitrogen --restore &
	xsetroot -cursor_name left_ptr
	
}
