#! /bin/sh

# Author 	 -  z0mbi3
# Source 	 -  https://github.com/gh0stzk/dotfiles
# Maintainer -  z0mbi3.zk@protonmail.com

bspdir="$HOME/.config/bspwm"
polydir="$HOME/.config/bspwm/rices/$RICETHEME/polybar"
export defnetif=$(ip route | grep '^default' | awk '{print $5}' | head -n1)

function launch() {
  local running
  running="$(pgrep -x "$1")"
  [ "$running" ] && kill -9 $(pgrep -x $1) 2> /dev/null
  eval "$* &"
}

function killeww() {
  if [[ `pidof eww` ]]; then 
		pkill eww
  fi
}

function ResetTermite() {
  if [[ `pidof termite` ]]; then 
		killall -USR1 termite
  fi
}

function ReloadTermite() {
  if [ -f "$HOME/.config/termite/config" ]; then
		cat $HOME/.config/bspwm/rices/$RICETHEME/termiterc > $HOME/.config/termite/config
		ResetTermite
  else
		mkdir -p $HOME/.config/termite/ && touch $HOME/.config/termite/config
		cat $HOME/.config/bspwm/rices/$RICETHEME/termiterc > $HOME/.config/termite/config
		ResetTermite
  fi
}

function SetBspwmConf() {
	bspc config border_width "$1"
	bspc config top_padding "$2"
	bspc config bottom_padding "$3"
	bspc config normal_border_color "$4" 
	bspc config active_border_color "$5"
	bspc config focused_border_color "$6"
	bspc config presel_feedback_color "$7"
	bspc config left_padding "$8"
	bspc config right_padding "$9"
}

function SetGirlFriendRice() {
	
	case $RICETHEME in
	
		emilia)
		
		  SetBspwmConf 0 60 5 "#414868" "#c0caf5" "#bb9af7" "#7aa2f7" 5 5
		  		  
		  killeww
		  launch polybar -q emi-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark 
		  
		  ;;
			
		jan)
		
		  SetBspwmConf 1 60 5 "#4C3A6D" "#4C3A6D" "#785DA5" "#070219" 5 5
		  
		  killeww
		  launch polybar -q main -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark
		  
		  ;;
		    
		aline)
		
		  SetBspwmConf 0 55 5 "#ca9ee6" "#ca9ee6" "#8CAAEE" "#E78284" 5 5
		  
		  killeww
		  launch polybar -q aline-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-light
		  
		  ;;
		  
		isabel)
		
		  SetBspwmConf 0 5 45 "#b8bfe5" "#b8bfe5" "#7560d3" "#81ae5f" 5 5
		  
		  killeww
		  launch polybar -q isa-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark
		  
		  ;;
		  
		cynthia)
		
		  SetBspwmConf 0 50 5 "#543f66" "#543f66" "#465b80" "#3f5273" 5 5
		  
		  killeww
		  launch polybar -q cyn-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark
		  
		  ;;
		  
		silvia)
		
		  SetBspwmConf 0 50 5 "#d3869b" "#d3869b" "#fbf1c7" "#b8bb26" 5 5

		  killeww
		  launch polybar -q cata-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark
		  
		  ;;
		
		melissa)
		
		  SetBspwmConf 0 42 40 "#e5e9f0" "#e5e9f0" "#4c566a" "#bf616a" 5 5	

		  killeww
		  launch polybar -q mel-bar -c ${polydir}/config.ini
		  polybar -q mel2-bar -c ${polydir}/config.ini &
		  launch dunst -config ${bspdir}/dunstrc-dark 
		  
		  ;;
		  
		pamela)
		
		  SetBspwmConf 0 60 5 "#C574DD" "#C574DD" "#8897F4" "#FF4971" 5 5
		  
		  killeww
		  launch polybar -q pam1 -c ${polydir}/config.ini
		  polybar -q pam2 -c ${polydir}/config.ini &
		  polybar -q pam3 -c ${polydir}/config.ini &
		  polybar -q pam4 -c ${polydir}/config.ini &
		  polybar -q pam5 -c ${polydir}/config.ini &
		  polybar -q pam6 -c ${polydir}/config.ini &
		  launch dunst -config ${bspdir}/dunstrc-dark
		  
		  ;;
		  
		cristina)
		
		  SetBspwmConf 0 10 60 "#9bced7" "#9bced7" "#c3a5e6" "#c3a5e6" 5 5
		  
		  killeww
		  launch polybar -q cristina-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark
		  
		  ;;
		  
		z0mbi3)
		
		  SetBspwmConf 0 5 5 "#3d414f" "#3d414f" "#3d414f" "#90ceaa" 80 5
		  
		  # Kill any running instances of bspc to prevent multiple
		  # instances of "workspaces" script in eww rices to run at once
		  killall -9 picom bspc
		  
		  launch eww -c $HOME/.config/bspwm/rices/z0mbi3/bar open bar
		  launch polybar -q tray -c ~/.config/bspwm/rices/z0mbi3/bar/polybar_tray.ini
		  launch dunst -config ${bspdir}/dunstrc-dark
		  
		  ;;
		  
		  karla)
		
		  SetBspwmConf 0 65 5 "#ff004a" "#ff004a" "#0864f1" "#b93fe0" 5 5
		 
		  kill -9 picom
		  launch eww -c $HOME/.config/bspwm/rices/karla/bar open bar
		  launch polybar -q karla-bar -c ${polydir}/config.ini
		  polybar -q karla-bar2 -c ${polydir}/config.ini &
		  launch dunst -config ${bspdir}/dunstrc-light
		  
		  ;;
		  
		andrea)
		
		  SetBspwmConf 0 60 5 "#161616" "#161616" "#605692" "#67d4f1" 5 5
		  
		  killall -9 picom polybar
		  launch dunst -config ${bspdir}/dunstrc-light
		  launch eww -c $HOME/.config/bspwm/rices/$RICETHEME/arin --restart open-many \
		   search \
		   apps \
		   weather \
		   music \
		   system
		  
		  ;;
		  
	esac		
}

ReloadTermite

function AutoStartApps() {
	
	launch sxhkd -c ${bspdir}/sxhkdrc
	launch picom --config ${bspdir}/rices/$RICETHEME/picom.conf
	#launch picom --legacy-backends --config ${bspdir}/rices/$RICETHEME/picom.conf
	launch /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
	RandomWall
	#nitrogen --restore &
	xsetroot -cursor_name left_ptr
	
}
