#!/usr/bin/env bash
#  ╦═╗╦╔═╗╔═╗  ╔═╗╔═╗╦  ╔═╗╔═╗╔╦╗╔═╗╦═╗  - z0mbi3
#  ╠╦╝║║  ║╣   ╚═╗║╣ ║  ║╣ ║   ║ ║ ║╠╦╝  - https://github.com/gh0stzk/dotfiles
#  ╩╚═╩╚═╝╚═╝  ╚═╝╚═╝╩═╝╚═╝╚═╝ ╩ ╚═╝╩╚═  - z0mbi3.zk@protonmail.com

cfg_file="$HOME/.config/bspwm/rice.cfg"
rofi_command="rofi -no-lazy-grab -dmenu -theme $HOME/.config/bspwm/scripts/RiceSelector.rasi"

# Array de opciones
options=("emilia" "jan" "aline" "isabel" "andrea" "cynthia" "silvia" "melissa" "pamela" "cristina" "karla" "z0mbi3")

# Mostrar el menú de selección de rofi y almacenar el resultado en una variable
selected=$(printf "%s\n" "${options[@]}" | $rofi_command)

# Si se seleccionó una opción válida, escribir el valor en el archivo de configuración y reiniciar el gestor de ventanas
for rice in ${selected}
do
	if [ -n "$selected" ]; then
		echo "$rice" > "${cfg_file}"
		sleep 0.50
		bspc wm -r
	else
		exit
	fi
done
