#!/usr/bin/env bash

# Author 	 -  z0mbi3
# Source 	 -  https://github.com/gh0stzk/dotfiles
# Maintainer -  z0mbi3.zk@protonmail.com

time=$(date '+%d-%B-%y-%H%M%S')
dir="$(xdg-user-dir PICTURES)/ScreenShots"
file="$time.png"

	if ! [ -d "$dir" ]; then
		mkdir -p $dir
	fi

function notify_view() {
	
	if [[ -e "$dir/$file" ]]; then
		notify-send -i "$dir/$file" -a shot -u low Screenshot "Screenshot Guardado!"
	else
		notify-send -i custom-trash-bin -a shot_icon -u low Screenshot "Screenshot Eliminado"
	fi
}

function pumpumshot() {
	
	cd "$dir" || return
	local bytes
    if [ "$(pgrep -x picom)" ]; then
      bytes="$(maim -u -o -m 4 -d 3 -f png -s -b 2 -c 0.35,0.55,0.85,0.25 -l | base64)"
    else
      bytes="$(maim -u -o -m 4 -d 3 -f png -s -b 2 | base64)" 
    fi
	if [ "$bytes" ]; then
		echo "$bytes" | base64 --decode | tee "$file"
		notify_view
	else
		notify-send -i custom-cancel -a shot_icon -u low Screenshot "Operacion Cancelada."
	fi
}

pumpumshot
