#!/usr/bin/env bash
#  ╔═╗╦═╗╔═╗╦ ╦  ╦ ╦╔═╗╔╦╗╔═╗╔╦╗╔═╗╔═╗
#  ╠═╣╠╦╝║  ╠═╣  ║ ║╠═╝ ║║╠═╣ ║ ║╣ ╚═╗
#  ╩ ╩╩╚═╚═╝╩ ╩  ╚═╝╩  ═╩╝╩ ╩ ╩ ╚═╝╚═╝
#	Script to check for new updates in arch and AUR. 
#   Author: z0mbi3
#	url: https://github.com/gh0stzk

updates=$(($(checkupdates 2> /dev/null | wc -l || echo 0) + $(yay -Qum 2> /dev/null | wc -l || echo 0)))
echo "${updates:-0}"
