#!/usr/bin/env bash

cache_file=$HOME/.cache/$(whoami)/airplane_state

initial_hook() {
	if [ ! -d "$(dirname "$cache_file")" ]; then
		mkdir -p "$(dirname "$cache_file")"
	fi
	if [ ! -f "$cache_file" ]; then
		echo Off >"$cache_file"
	fi
}

get_state() {
	# check if airplane-mode is running
	cat "$cache_file"
}

icon() {
  local state=$(get_state)
	if [[ $state == "On" ]]; then
		echo "󰀞"
	else
		echo "󰀝"
	fi
}

airplane_on() {
	nmcli networking off
	if which bluetoothctl; then
		bluetoothctl power off
	fi
	notify-send --urgency=normal -i airplane-mode "Airplane Mode" "Airplane mode has been turned on!"
  echo On >"$cache_file"
}

airplane_off() {
	nmcli networking on
	if which bluetoothctl; then
		bluetoothctl power on
	fi
	notify-send --urgency=normal -i airplane-mode "Airplane Mode" "Airplane mode has been turned off!"
  echo Off >"$cache_file"
}

toggle() {
  local state=$(get_state)
	if [[ $state == "Off" ]]; then
		airplane_on
	else
		airplane_off
	fi
}

initial_hook

if [[ $1 == "--toggle" ]]; then
	toggle
elif [[ $1 == "--icon" ]]; then
	icon
elif [[ $1 == "--status" ]]; then
	get_state
fi
