#!/usr/bin/env bash
#  ██╗  ██╗ █████╗ ██████╗ ██╗      █████╗     ██████╗ ██╗ ██████╗███████╗
#  ██║ ██╔╝██╔══██╗██╔══██╗██║     ██╔══██╗    ██╔══██╗██║██╔════╝██╔════╝
#  █████╔╝ ███████║██████╔╝██║     ███████║    ██████╔╝██║██║     █████╗
#  ██╔═██╗ ██╔══██║██╔══██╗██║     ██╔══██║    ██╔══██╗██║██║     ██╔══╝
#  ██║  ██╗██║  ██║██║  ██║███████╗██║  ██║    ██║  ██║██║╚██████╗███████╗
#  ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝    ╚═╝  ╚═╝╚═╝ ╚═════╝╚══════╝
#  Author  :  z0mbi3
#  Url     :  https://github.com/gh0stzk/dotfiles
#  About   :  This file will configure and launch the rice.
#

# Set bspwm configuration for Karla
set_bspwm_config() {
	bspc config border_width 3
	bspc config top_padding 48
	bspc config bottom_padding 2
	bspc config left_padding 2
	bspc config right_padding 2
	bspc config normal_border_color "#21222c"
	bspc config active_border_color "#353c52"
	bspc config focused_border_color "#353c52"
	bspc config presel_feedback_color "#8656e3"
}

# Set alacritty colorscheme
set_alacritty_config() {
	cat >"$HOME"/.config/alacritty/rice-colors.toml <<EOF
# (Zombie-Night) Color scheme for Karla Rice

# Default colors
[colors.primary]
background = "#0E1113"
foreground = "#afb1db"

# Cursor colors
[colors.cursor]
cursor = "#8656e3"
text = "#0b0b12"

# Normal colors
[colors.normal]
black = "#2d2b36"
blue = "#5884d4"
cyan = "#7df0f0"
green = "#61b33e"
magenta = "#7a44e3"
red = "#e7034a"
white = "#faf7ff"
yellow = "#ffb964"

# Bright colors
[colors.bright]
black = "#373542"
blue = "#5f90ea"
cyan = "#97f0f0"
green = "#6fb352"
magenta = "#8656e3"
red = "#e71c5b"
white = "#fdfcff"
yellow = "#ffb964"
EOF
}

# Set kitty colorscheme
set_kitty_config() {
  cat >"$HOME"/.config/kitty/current-theme.conf <<EOF
## This file is autogenerated, do not edit it, instead edit the Theme.sh file inside the rice directory.
## (z0mbi3-Night) color scheme for Karla rice


# The basic colors
foreground              #afb1db
background              #0E1113
selection_foreground    #afb1db
selection_background    #8656e3

# Cursor colors
cursor                  #8656e3
cursor_text_color       #0b0b12

# URL underline color when hovering with mouse
url_color               #7df0f0

# Kitty window border colors
active_border_color     #7a44e3
inactive_border_color   #373542
bell_border_color       #ffb964

# Tab bar colors
active_tab_foreground   #afb1db
active_tab_background   #7a44e3
inactive_tab_foreground #afb1db
inactive_tab_background #2d2b36
tab_bar_background      #0E1113

# The 16 terminal colors

# black
color0 #2d2b36
color8 #373542

# red
color1 #e7034a
color9 #e71c5b

# green
color2  #61b33e
color10 #6fb352

# yellow
color3  #ffb964
color11 #ffb964

# blue
color4  #5884d4
color12 #5f90ea

# magenta
color5  #7a44e3
color13 #8656e3

# cyan
color6  #7df0f0
color14 #97f0f0

# white
color7  #faf7ff
color15 #fdfcff
EOF

killall -USR1 kitty
}

# Set compositor configuration
set_picom_config() {
	sed -i "$HOME"/.config/bspwm/picom.conf \
		-e "s/normal = .*/normal =  { fade = false; shadow = false; }/g" \
		-e "s/shadow-color = .*/shadow-color = \"#000000\"/g" \
		-e "s/corner-radius = .*/corner-radius = 0/g" \
		-e "s/\".*:class_g = 'Alacritty'\"/\"95:class_g = 'Alacritty'\"/g" \
		-e "s/\".*:class_g = 'kitty'\"/\"95:class_g = 'kitty'\"/g" \
		-e "s/\".*:class_g = 'FloaTerm'\"/\"95:class_g = 'FloaTerm'\"/g"
}

# Set dunst notification daemon config
set_dunst_config() {
	sed -i "$HOME"/.config/bspwm/dunstrc \
		-e "s/transparency = .*/transparency = 8/g" \
		-e "s/frame_color = .*/frame_color = \"#0E1113\"/g" \
		-e "s/separator_color = .*/separator_color = \"#353c52\"/g" \
		-e "s/font = .*/font = JetBrainsMono NF Medium 9/g" \
		-e "s/foreground='.*'/foreground='#7a44e3'/g"

	sed -i '/urgency_low/Q' "$HOME"/.config/bspwm/dunstrc
	cat >>"$HOME"/.config/bspwm/dunstrc <<-_EOF_
		[urgency_low]
		timeout = 3
		background = "#0E1113"
		foreground = "#afb1db"

		[urgency_normal]
		timeout = 6
		background = "#0E1113"
		foreground = "#afb1db"

		[urgency_critical]
		timeout = 0
		background = "#0E1113"
		foreground = "#afb1db"
	_EOF_
}

# Set eww colors
set_eww_colors() {
	cat >"$HOME"/.config/bspwm/eww/colors.scss <<EOF
// Eww colors for Karla rice
\$bg: #0E1113;
\$bg-alt: #111517;
\$fg: #afb1db;
\$black: #373542;
\$lightblack: #262831;
\$red: #e7034a;
\$blue: #5884d4;
\$cyan: #7df0f0;
\$magenta: #7a44e3;
\$green: #61b33e;
\$yellow: #ffb964;
\$archicon: #0f94d2;
EOF
}

# Set jgmenu colors for Karla
set_jgmenu_colors() {
	sed -i "$HOME"/.config/bspwm/jgmenurc \
		-e 's/color_menu_bg = .*/color_menu_bg = #0E1113/' \
		-e 's/color_norm_fg = .*/color_norm_fg = #afb1db/' \
		-e 's/color_sel_bg = .*/color_sel_bg = #111517/' \
		-e 's/color_sel_fg = .*/color_sel_fg = #afb1db/' \
		-e 's/color_sep_fg = .*/color_sep_fg = #373542/'
}

# Set rofi colors
set_launcher_config() {
	cat >"$HOME"/.config/bspwm/src/rofi-themes/shared.rasi <<EOF
// Rofi colors for Karla

* {
    font: "JetBrainsMono NF Bold 9";
    background: #0E1113F7;
    background-alt: #0E1113F5;
    foreground: #afb1db;
    selected: #5884d4;
    active: #61b33e;
    urgent: #e71c5b;
    
    img-background: url("~/.config/bspwm/rices/karla/rofi.webp", width);
}
EOF
}

# Launch the bar
launch_bars() {

	for mon in $(polybar --list-monitors | cut -d":" -f1); do
		(MONITOR=$mon polybar -q karla-bar -c "${rice_dir}"/config.ini) &
		(MONITOR=$mon polybar -q karla-bar2 -c "${rice_dir}"/config.ini) &
		(MONITOR=$mon polybar -q karla-bar3 -c "${rice_dir}"/config.ini) &
	done

}

### ---------- Apply Configurations ---------- ###

set_bspwm_config
set_alacritty_config
set_kitty_config
set_picom_config
launch_bars
set_dunst_config
set_eww_colors
set_jgmenu_colors
set_launcher_config
