#!/usr/bin/env bash
#  ███████╗ ██████╗ ███╗   ███╗██████╗ ██╗██████╗     ██████╗ ██╗ ██████╗███████╗
#  ╚══███╔╝██╔═████╗████╗ ████║██╔══██╗██║╚════██╗    ██╔══██╗██║██╔════╝██╔════╝
#    ███╔╝ ██║██╔██║██╔████╔██║██████╔╝██║ █████╔╝    ██████╔╝██║██║     █████╗
#   ███╔╝  ████╔╝██║██║╚██╔╝██║██╔══██╗██║ ╚═══██╗    ██╔══██╗██║██║     ██╔══╝
#  ███████╗╚██████╔╝██║ ╚═╝ ██║██████╔╝██║██████╔╝    ██║  ██║██║╚██████╗███████╗
#  ╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚═════╝ ╚═╝╚═════╝     ╚═╝  ╚═╝╚═╝ ╚═════╝╚══════╝
#  Author  :  z0mbi3
#  Url     :  https://github.com/gh0stzk/dotfiles
#  About   :  This file will configure and launch the rice.
#

# Set bspwm configuration for z0mbi3
set_bspwm_config() {
	bspc config border_width 0
	bspc config top_padding 3
	bspc config bottom_padding 2
	bspc config left_padding 68
	bspc config right_padding 2
	bspc config normal_border_color "#3d414f"
	bspc config active_border_color "#3d414f"
	bspc config focused_border_color "#3d414f"
	bspc config presel_feedback_color "#90ceaa"
}

pidof -q bspc && pkill -9 bspc >/dev/null

# Set alacritty colorscheme
set_alacritty_config() {
	cat >"$HOME"/.config/alacritty/rice-colors.toml <<EOF
# (Decay, decayce variant) Color scheme for z0mbi3 Rice

# Default colors
[colors.primary]
background = "#0d0f18"
foreground = "#a5b6cf"

# Cursor colors
[colors.cursor]
cursor = "#a5b6cf"
text = "#0d0f18"

# Normal colors
[colors.normal]
black = "#3d414f"
blue = "#86aaec"
cyan = "#93cee9"
green = "#90ceaa"
magenta = "#c296eb"
red = "#dd6777"
white = "#cbced3"
yellow = "#ecd3a0"

# Bright colors
[colors.bright]
black = "#3d414f"
blue = "#86aaec"
cyan = "#93cee9"
green = "#90ceaa"
magenta = "#c296eb"
red = "#dd6777"
white = "#cbced3"
yellow = "#ecd3a0"
EOF
}

# Set kitty colorscheme
set_kitty_config() {
  cat >"$HOME"/.config/kitty/current-theme.conf <<EOF
## This file is autogenerated, do not edit it, instead edit the Theme.sh file inside the rice directory.
## (Decay, decayce variant) Color scheme for z0mbi3 Rice


# The basic colors
foreground              #a5b6cf
background              #0d0f18
selection_foreground    #0d0f18
selection_background    #c296eb

# Cursor colors
cursor                  #a5b6cf
cursor_text_color       #0d0f18

# URL underline color when hovering with mouse
url_color               #86aaec

# Kitty window border colors
active_border_color     #c296eb
inactive_border_color   #3d414f
bell_border_color       #ecd3a0

# Tab bar colors
active_tab_foreground   #0d0f18
active_tab_background   #c296eb
inactive_tab_foreground #a5b6cf
inactive_tab_background #3d414f
tab_bar_background      #0d0f18

# The 16 terminal colors

# black
color0 #3d414f
color8 #3d414f

# red
color1 #dd6777
color9 #dd6777

# green
color2  #90ceaa
color10 #90ceaa

# yellow
color3  #ecd3a0
color11 #ecd3a0

# blue
color4  #86aaec
color12 #86aaec

# magenta
color5  #c296eb
color13 #c296eb

# cyan
color6  #93cee9
color14 #93cee9

# white
color7  #cbced3
color15 #cbced3
EOF

kill -USR1 kitty
}

# Set compositor configuration
set_picom_config() {
	sed -i "$HOME"/.config/bspwm/picom.conf \
		-e "s/normal = .*/normal =  { fade = true; shadow = true; }/g" \
		-e "s/shadow-color = .*/shadow-color = \"#000000\"/g" \
		-e "s/corner-radius = .*/corner-radius = 6/g" \
		-e "s/\".*:class_g = 'Alacritty'\"/\"100:class_g = 'Alacritty'\"/g" \
		-e "s/\".*:class_g = 'kitty'\"/\"100:class_g = 'kitty'\"/g" \
		-e "s/\".*:class_g = 'FloaTerm'\"/\"100:class_g = 'FloaTerm'\"/g"
}

# Set dunst notification daemon config
set_dunst_config() {
	sed -i "$HOME"/.config/bspwm/dunstrc \
		-e "s/transparency = .*/transparency = 0/g" \
		-e "s/frame_color = .*/frame_color = \"#0d0f18\"/g" \
		-e "s/separator_color = .*/separator_color = \"#3d414f\"/g" \
		-e "s/font = .*/font = JetBrainsMono NF Medium 9/g" \
		-e "s/foreground='.*'/foreground='#c296eb'/g"

	sed -i '/urgency_low/Q' "$HOME"/.config/bspwm/dunstrc
	cat >>"$HOME"/.config/bspwm/dunstrc <<-_EOF_
		[urgency_low]
		timeout = 3
		background = "#0d0f18"
		foreground = "#a5b6cf"

		[urgency_normal]
		timeout = 6
		background = "#0d0f18"
		foreground = "#a5b6cf"

		[urgency_critical]
		timeout = 0
		background = "#0d0f18"
		foreground = "#a5b6cf"
	_EOF_
}

# Set eww colors
set_eww_colors() {
	cat >"$HOME"/.config/bspwm/eww/colors.scss <<EOF
// Eww colors for z0mbi3 rice
\$bg: #0d0f18;
\$bg-alt: #151720;
\$fg: #a5b6cf;
\$black: #3d414f;
\$lightblack: #262831;
\$red: #dd6777;
\$blue: #86aaec;
\$cyan: #93cee9;
\$magenta: #c296eb;
\$green: #90ceaa;
\$yellow: #ecd3a0;
\$archicon: #0f94d2;
EOF
}

# Set jgmenu colors for z0mbi3
set_jgmenu_colors() {
	sed -i "$HOME"/.config/bspwm/jgmenurc \
		-e 's/color_menu_bg = .*/color_menu_bg = #0d0f18/' \
		-e 's/color_norm_fg = .*/color_norm_fg = #a5b6cf/' \
		-e 's/color_sel_bg = .*/color_sel_bg = #151720/' \
		-e 's/color_sel_fg = .*/color_sel_fg = #a5b6cf/' \
		-e 's/color_sep_fg = .*/color_sep_fg = #3d414f/'
}

# Set rofi colors
set_launcher_config() {
	cat >"$HOME"/.config/bspwm/src/rofi-themes/shared.rasi <<EOF
// Rofi colors for z0mbi3

* {
    font: "JetBrainsMono NF Bold 9";
    background: #0d0f18;
    background-alt: #0d0f18C7;
    foreground: #a5b6cf;
    selected: #c296eb;
    active: #90ceaa;
    urgent: #dd6777;
    
    img-background: url("~/.config/bspwm/rices/z0mbi3/rofi.webp", width);
}
EOF
}

# Launch the bar and or eww widgets
launch_bars() {
	eww -c "${rice_dir}"/bar open --toggle bar
}

### ---------- Apply Configurations ---------- ###

set_bspwm_config
set_alacritty_config
set_kitty_config
set_picom_config
set_dunst_config
set_eww_colors
set_jgmenu_colors
set_launcher_config
launch_bars
